// Code generated by ent, DO NOT EDIT.

package companionconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the companionconfig type in the database.
	Label = "companion_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarType holds the string denoting the avatar_type field in the database.
	FieldAvatarType = "avatar_type"
	// FieldPersonalityType holds the string denoting the personality_type field in the database.
	FieldPersonalityType = "personality_type"
	// FieldEncouragementStyle holds the string denoting the encouragement_style field in the database.
	FieldEncouragementStyle = "encouragement_style"
	// FieldVoiceType holds the string denoting the voice_type field in the database.
	FieldVoiceType = "voice_type"
	// FieldGrowthLevel holds the string denoting the growth_level field in the database.
	FieldGrowthLevel = "growth_level"
	// FieldRelationshipScore holds the string denoting the relationship_score field in the database.
	FieldRelationshipScore = "relationship_score"
	// FieldCharacterID holds the string denoting the character_id field in the database.
	FieldCharacterID = "character_id"
	// FieldCustomName holds the string denoting the custom_name field in the database.
	FieldCustomName = "custom_name"
	// FieldCustomAvatarURL holds the string denoting the custom_avatar_url field in the database.
	FieldCustomAvatarURL = "custom_avatar_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the companionconfig in the database.
	Table = "companion_configs"
)

// Columns holds all SQL columns for companionconfig fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldAvatarType,
	FieldPersonalityType,
	FieldEncouragementStyle,
	FieldVoiceType,
	FieldGrowthLevel,
	FieldRelationshipScore,
	FieldCharacterID,
	FieldCustomName,
	FieldCustomAvatarURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultAvatarType holds the default value on creation for the "avatar_type" field.
	DefaultAvatarType string
	// DefaultPersonalityType holds the default value on creation for the "personality_type" field.
	DefaultPersonalityType string
	// DefaultEncouragementStyle holds the default value on creation for the "encouragement_style" field.
	DefaultEncouragementStyle string
	// DefaultGrowthLevel holds the default value on creation for the "growth_level" field.
	DefaultGrowthLevel int
	// DefaultRelationshipScore holds the default value on creation for the "relationship_score" field.
	DefaultRelationshipScore float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CompanionConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatarType orders the results by the avatar_type field.
func ByAvatarType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarType, opts...).ToFunc()
}

// ByPersonalityType orders the results by the personality_type field.
func ByPersonalityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPersonalityType, opts...).ToFunc()
}

// ByEncouragementStyle orders the results by the encouragement_style field.
func ByEncouragementStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncouragementStyle, opts...).ToFunc()
}

// ByVoiceType orders the results by the voice_type field.
func ByVoiceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoiceType, opts...).ToFunc()
}

// ByGrowthLevel orders the results by the growth_level field.
func ByGrowthLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrowthLevel, opts...).ToFunc()
}

// ByRelationshipScore orders the results by the relationship_score field.
func ByRelationshipScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelationshipScore, opts...).ToFunc()
}

// ByCharacterID orders the results by the character_id field.
func ByCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCharacterID, opts...).ToFunc()
}

// ByCustomName orders the results by the custom_name field.
func ByCustomName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomName, opts...).ToFunc()
}

// ByCustomAvatarURL orders the results by the custom_avatar_url field.
func ByCustomAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomAvatarURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
