// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/chatmessage"
)

// ChatMessageCreate is the builder for creating a ChatMessage entity.
type ChatMessageCreate struct {
	config
	mutation *ChatMessageMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ChatMessageCreate) SetUserID(v uuid.UUID) *ChatMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *ChatMessageCreate) SetCharacterID(v string) *ChatMessageCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCharacterID(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetCharacterID(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *ChatMessageCreate) SetRole(v string) *ChatMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChatMessageCreate) SetContent(v string) *ChatMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetIsComplete sets the "is_complete" field.
func (_c *ChatMessageCreate) SetIsComplete(v bool) *ChatMessageCreate {
	_c.mutation.SetIsComplete(v)
	return _c
}

// SetNillableIsComplete sets the "is_complete" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableIsComplete(v *bool) *ChatMessageCreate {
	if v != nil {
		_c.SetIsComplete(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatMessageCreate) SetCreatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCreatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatMessageCreate) SetID(v uuid.UUID) *ChatMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableID(v *uuid.UUID) *ChatMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_c *ChatMessageCreate) Mutation() *ChatMessageMutation {
	return _c.mutation
}

// Save creates the ChatMessage in the database.
func (_c *ChatMessageCreate) Save(ctx context.Context) (*ChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMessageCreate) SaveX(ctx context.Context) *ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMessageCreate) defaults() {
	if _, ok := _c.mutation.IsComplete(); !ok {
		v := chatmessage.DefaultIsComplete
		_c.mutation.SetIsComplete(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chatmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMessageCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatMessage.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChatMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsComplete(); !ok {
		return &ValidationError{Name: "is_complete", err: errors.New(`ent: missing required field "ChatMessage.is_complete"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatMessage.created_at"`)}
	}
	return nil
}

func (_c *ChatMessageCreate) sqlSave(ctx context.Context) (*ChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMessageCreate) createSpec() (*ChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmessage.Table, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(chatmessage.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(chatmessage.FieldCharacterID, field.TypeString, value)
		_node.CharacterID = &value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.IsComplete(); ok {
		_spec.SetField(chatmessage.FieldIsComplete, field.TypeBool, value)
		_node.IsComplete = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ChatMessageCreateBulk is the builder for creating many ChatMessage entities in bulk.
type ChatMessageCreateBulk struct {
	config
	err      error
	builders []*ChatMessageCreate
}

// Save creates the ChatMessage entities in the database.
func (_c *ChatMessageCreateBulk) Save(ctx context.Context) ([]*ChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) SaveX(ctx context.Context) []*ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
