// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/lagom/lagom-server/ent/celebritycharacter"
	"github.com/lagom/lagom-server/ent/chatmessage"
	"github.com/lagom/lagom-server/ent/companionconfig"
	"github.com/lagom/lagom-server/ent/dailycompletion"
	"github.com/lagom/lagom-server/ent/dailylog"
	"github.com/lagom/lagom-server/ent/focussession"
	"github.com/lagom/lagom-server/ent/habit"
	"github.com/lagom/lagom-server/ent/microaction"
	"github.com/lagom/lagom-server/ent/user"
	"github.com/lagom/lagom-server/ent/usercharacterconfig"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CelebrityCharacter is the client for interacting with the CelebrityCharacter builders.
	CelebrityCharacter *CelebrityCharacterClient
	// ChatMessage is the client for interacting with the ChatMessage builders.
	ChatMessage *ChatMessageClient
	// CompanionConfig is the client for interacting with the CompanionConfig builders.
	CompanionConfig *CompanionConfigClient
	// DailyCompletion is the client for interacting with the DailyCompletion builders.
	DailyCompletion *DailyCompletionClient
	// DailyLog is the client for interacting with the DailyLog builders.
	DailyLog *DailyLogClient
	// FocusSession is the client for interacting with the FocusSession builders.
	FocusSession *FocusSessionClient
	// Habit is the client for interacting with the Habit builders.
	Habit *HabitClient
	// MicroAction is the client for interacting with the MicroAction builders.
	MicroAction *MicroActionClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserCharacterConfig is the client for interacting with the UserCharacterConfig builders.
	UserCharacterConfig *UserCharacterConfigClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CelebrityCharacter = NewCelebrityCharacterClient(c.config)
	c.ChatMessage = NewChatMessageClient(c.config)
	c.CompanionConfig = NewCompanionConfigClient(c.config)
	c.DailyCompletion = NewDailyCompletionClient(c.config)
	c.DailyLog = NewDailyLogClient(c.config)
	c.FocusSession = NewFocusSessionClient(c.config)
	c.Habit = NewHabitClient(c.config)
	c.MicroAction = NewMicroActionClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserCharacterConfig = NewUserCharacterConfigClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		CelebrityCharacter:  NewCelebrityCharacterClient(cfg),
		ChatMessage:         NewChatMessageClient(cfg),
		CompanionConfig:     NewCompanionConfigClient(cfg),
		DailyCompletion:     NewDailyCompletionClient(cfg),
		DailyLog:            NewDailyLogClient(cfg),
		FocusSession:        NewFocusSessionClient(cfg),
		Habit:               NewHabitClient(cfg),
		MicroAction:         NewMicroActionClient(cfg),
		User:                NewUserClient(cfg),
		UserCharacterConfig: NewUserCharacterConfigClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		CelebrityCharacter:  NewCelebrityCharacterClient(cfg),
		ChatMessage:         NewChatMessageClient(cfg),
		CompanionConfig:     NewCompanionConfigClient(cfg),
		DailyCompletion:     NewDailyCompletionClient(cfg),
		DailyLog:            NewDailyLogClient(cfg),
		FocusSession:        NewFocusSessionClient(cfg),
		Habit:               NewHabitClient(cfg),
		MicroAction:         NewMicroActionClient(cfg),
		User:                NewUserClient(cfg),
		UserCharacterConfig: NewUserCharacterConfigClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CelebrityCharacter.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CelebrityCharacter, c.ChatMessage, c.CompanionConfig, c.DailyCompletion,
		c.DailyLog, c.FocusSession, c.Habit, c.MicroAction, c.User,
		c.UserCharacterConfig,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CelebrityCharacter, c.ChatMessage, c.CompanionConfig, c.DailyCompletion,
		c.DailyLog, c.FocusSession, c.Habit, c.MicroAction, c.User,
		c.UserCharacterConfig,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CelebrityCharacterMutation:
		return c.CelebrityCharacter.mutate(ctx, m)
	case *ChatMessageMutation:
		return c.ChatMessage.mutate(ctx, m)
	case *CompanionConfigMutation:
		return c.CompanionConfig.mutate(ctx, m)
	case *DailyCompletionMutation:
		return c.DailyCompletion.mutate(ctx, m)
	case *DailyLogMutation:
		return c.DailyLog.mutate(ctx, m)
	case *FocusSessionMutation:
		return c.FocusSession.mutate(ctx, m)
	case *HabitMutation:
		return c.Habit.mutate(ctx, m)
	case *MicroActionMutation:
		return c.MicroAction.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserCharacterConfigMutation:
		return c.UserCharacterConfig.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CelebrityCharacterClient is a client for the CelebrityCharacter schema.
type CelebrityCharacterClient struct {
	config
}

// NewCelebrityCharacterClient returns a client for the CelebrityCharacter from the given config.
func NewCelebrityCharacterClient(c config) *CelebrityCharacterClient {
	return &CelebrityCharacterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `celebritycharacter.Hooks(f(g(h())))`.
func (c *CelebrityCharacterClient) Use(hooks ...Hook) {
	c.hooks.CelebrityCharacter = append(c.hooks.CelebrityCharacter, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `celebritycharacter.Intercept(f(g(h())))`.
func (c *CelebrityCharacterClient) Intercept(interceptors ...Interceptor) {
	c.inters.CelebrityCharacter = append(c.inters.CelebrityCharacter, interceptors...)
}

// Create returns a builder for creating a CelebrityCharacter entity.
func (c *CelebrityCharacterClient) Create() *CelebrityCharacterCreate {
	mutation := newCelebrityCharacterMutation(c.config, OpCreate)
	return &CelebrityCharacterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CelebrityCharacter entities.
func (c *CelebrityCharacterClient) CreateBulk(builders ...*CelebrityCharacterCreate) *CelebrityCharacterCreateBulk {
	return &CelebrityCharacterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CelebrityCharacterClient) MapCreateBulk(slice any, setFunc func(*CelebrityCharacterCreate, int)) *CelebrityCharacterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CelebrityCharacterCreateBulk{err: fmt.Errorf("calling to CelebrityCharacterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CelebrityCharacterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CelebrityCharacterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CelebrityCharacter.
func (c *CelebrityCharacterClient) Update() *CelebrityCharacterUpdate {
	mutation := newCelebrityCharacterMutation(c.config, OpUpdate)
	return &CelebrityCharacterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CelebrityCharacterClient) UpdateOne(_m *CelebrityCharacter) *CelebrityCharacterUpdateOne {
	mutation := newCelebrityCharacterMutation(c.config, OpUpdateOne, withCelebrityCharacter(_m))
	return &CelebrityCharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CelebrityCharacterClient) UpdateOneID(id string) *CelebrityCharacterUpdateOne {
	mutation := newCelebrityCharacterMutation(c.config, OpUpdateOne, withCelebrityCharacterID(id))
	return &CelebrityCharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CelebrityCharacter.
func (c *CelebrityCharacterClient) Delete() *CelebrityCharacterDelete {
	mutation := newCelebrityCharacterMutation(c.config, OpDelete)
	return &CelebrityCharacterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CelebrityCharacterClient) DeleteOne(_m *CelebrityCharacter) *CelebrityCharacterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CelebrityCharacterClient) DeleteOneID(id string) *CelebrityCharacterDeleteOne {
	builder := c.Delete().Where(celebritycharacter.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CelebrityCharacterDeleteOne{builder}
}

// Query returns a query builder for CelebrityCharacter.
func (c *CelebrityCharacterClient) Query() *CelebrityCharacterQuery {
	return &CelebrityCharacterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCelebrityCharacter},
		inters: c.Interceptors(),
	}
}

// Get returns a CelebrityCharacter entity by its id.
func (c *CelebrityCharacterClient) Get(ctx context.Context, id string) (*CelebrityCharacter, error) {
	return c.Query().Where(celebritycharacter.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CelebrityCharacterClient) GetX(ctx context.Context, id string) *CelebrityCharacter {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CelebrityCharacterClient) Hooks() []Hook {
	return c.hooks.CelebrityCharacter
}

// Interceptors returns the client interceptors.
func (c *CelebrityCharacterClient) Interceptors() []Interceptor {
	return c.inters.CelebrityCharacter
}

func (c *CelebrityCharacterClient) mutate(ctx context.Context, m *CelebrityCharacterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CelebrityCharacterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CelebrityCharacterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CelebrityCharacterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CelebrityCharacterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CelebrityCharacter mutation op: %q", m.Op())
	}
}

// ChatMessageClient is a client for the ChatMessage schema.
type ChatMessageClient struct {
	config
}

// NewChatMessageClient returns a client for the ChatMessage from the given config.
func NewChatMessageClient(c config) *ChatMessageClient {
	return &ChatMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chatmessage.Hooks(f(g(h())))`.
func (c *ChatMessageClient) Use(hooks ...Hook) {
	c.hooks.ChatMessage = append(c.hooks.ChatMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chatmessage.Intercept(f(g(h())))`.
func (c *ChatMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChatMessage = append(c.inters.ChatMessage, interceptors...)
}

// Create returns a builder for creating a ChatMessage entity.
func (c *ChatMessageClient) Create() *ChatMessageCreate {
	mutation := newChatMessageMutation(c.config, OpCreate)
	return &ChatMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChatMessage entities.
func (c *ChatMessageClient) CreateBulk(builders ...*ChatMessageCreate) *ChatMessageCreateBulk {
	return &ChatMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChatMessageClient) MapCreateBulk(slice any, setFunc func(*ChatMessageCreate, int)) *ChatMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChatMessageCreateBulk{err: fmt.Errorf("calling to ChatMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChatMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChatMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChatMessage.
func (c *ChatMessageClient) Update() *ChatMessageUpdate {
	mutation := newChatMessageMutation(c.config, OpUpdate)
	return &ChatMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChatMessageClient) UpdateOne(_m *ChatMessage) *ChatMessageUpdateOne {
	mutation := newChatMessageMutation(c.config, OpUpdateOne, withChatMessage(_m))
	return &ChatMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChatMessageClient) UpdateOneID(id uuid.UUID) *ChatMessageUpdateOne {
	mutation := newChatMessageMutation(c.config, OpUpdateOne, withChatMessageID(id))
	return &ChatMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChatMessage.
func (c *ChatMessageClient) Delete() *ChatMessageDelete {
	mutation := newChatMessageMutation(c.config, OpDelete)
	return &ChatMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChatMessageClient) DeleteOne(_m *ChatMessage) *ChatMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChatMessageClient) DeleteOneID(id uuid.UUID) *ChatMessageDeleteOne {
	builder := c.Delete().Where(chatmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChatMessageDeleteOne{builder}
}

// Query returns a query builder for ChatMessage.
func (c *ChatMessageClient) Query() *ChatMessageQuery {
	return &ChatMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChatMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a ChatMessage entity by its id.
func (c *ChatMessageClient) Get(ctx context.Context, id uuid.UUID) (*ChatMessage, error) {
	return c.Query().Where(chatmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChatMessageClient) GetX(ctx context.Context, id uuid.UUID) *ChatMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChatMessageClient) Hooks() []Hook {
	return c.hooks.ChatMessage
}

// Interceptors returns the client interceptors.
func (c *ChatMessageClient) Interceptors() []Interceptor {
	return c.inters.ChatMessage
}

func (c *ChatMessageClient) mutate(ctx context.Context, m *ChatMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChatMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChatMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChatMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChatMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChatMessage mutation op: %q", m.Op())
	}
}

// CompanionConfigClient is a client for the CompanionConfig schema.
type CompanionConfigClient struct {
	config
}

// NewCompanionConfigClient returns a client for the CompanionConfig from the given config.
func NewCompanionConfigClient(c config) *CompanionConfigClient {
	return &CompanionConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `companionconfig.Hooks(f(g(h())))`.
func (c *CompanionConfigClient) Use(hooks ...Hook) {
	c.hooks.CompanionConfig = append(c.hooks.CompanionConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `companionconfig.Intercept(f(g(h())))`.
func (c *CompanionConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.CompanionConfig = append(c.inters.CompanionConfig, interceptors...)
}

// Create returns a builder for creating a CompanionConfig entity.
func (c *CompanionConfigClient) Create() *CompanionConfigCreate {
	mutation := newCompanionConfigMutation(c.config, OpCreate)
	return &CompanionConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CompanionConfig entities.
func (c *CompanionConfigClient) CreateBulk(builders ...*CompanionConfigCreate) *CompanionConfigCreateBulk {
	return &CompanionConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CompanionConfigClient) MapCreateBulk(slice any, setFunc func(*CompanionConfigCreate, int)) *CompanionConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CompanionConfigCreateBulk{err: fmt.Errorf("calling to CompanionConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CompanionConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CompanionConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CompanionConfig.
func (c *CompanionConfigClient) Update() *CompanionConfigUpdate {
	mutation := newCompanionConfigMutation(c.config, OpUpdate)
	return &CompanionConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CompanionConfigClient) UpdateOne(_m *CompanionConfig) *CompanionConfigUpdateOne {
	mutation := newCompanionConfigMutation(c.config, OpUpdateOne, withCompanionConfig(_m))
	return &CompanionConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CompanionConfigClient) UpdateOneID(id uuid.UUID) *CompanionConfigUpdateOne {
	mutation := newCompanionConfigMutation(c.config, OpUpdateOne, withCompanionConfigID(id))
	return &CompanionConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CompanionConfig.
func (c *CompanionConfigClient) Delete() *CompanionConfigDelete {
	mutation := newCompanionConfigMutation(c.config, OpDelete)
	return &CompanionConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CompanionConfigClient) DeleteOne(_m *CompanionConfig) *CompanionConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CompanionConfigClient) DeleteOneID(id uuid.UUID) *CompanionConfigDeleteOne {
	builder := c.Delete().Where(companionconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CompanionConfigDeleteOne{builder}
}

// Query returns a query builder for CompanionConfig.
func (c *CompanionConfigClient) Query() *CompanionConfigQuery {
	return &CompanionConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCompanionConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a CompanionConfig entity by its id.
func (c *CompanionConfigClient) Get(ctx context.Context, id uuid.UUID) (*CompanionConfig, error) {
	return c.Query().Where(companionconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CompanionConfigClient) GetX(ctx context.Context, id uuid.UUID) *CompanionConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CompanionConfigClient) Hooks() []Hook {
	return c.hooks.CompanionConfig
}

// Interceptors returns the client interceptors.
func (c *CompanionConfigClient) Interceptors() []Interceptor {
	return c.inters.CompanionConfig
}

func (c *CompanionConfigClient) mutate(ctx context.Context, m *CompanionConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CompanionConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CompanionConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CompanionConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CompanionConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CompanionConfig mutation op: %q", m.Op())
	}
}

// DailyCompletionClient is a client for the DailyCompletion schema.
type DailyCompletionClient struct {
	config
}

// NewDailyCompletionClient returns a client for the DailyCompletion from the given config.
func NewDailyCompletionClient(c config) *DailyCompletionClient {
	return &DailyCompletionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dailycompletion.Hooks(f(g(h())))`.
func (c *DailyCompletionClient) Use(hooks ...Hook) {
	c.hooks.DailyCompletion = append(c.hooks.DailyCompletion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dailycompletion.Intercept(f(g(h())))`.
func (c *DailyCompletionClient) Intercept(interceptors ...Interceptor) {
	c.inters.DailyCompletion = append(c.inters.DailyCompletion, interceptors...)
}

// Create returns a builder for creating a DailyCompletion entity.
func (c *DailyCompletionClient) Create() *DailyCompletionCreate {
	mutation := newDailyCompletionMutation(c.config, OpCreate)
	return &DailyCompletionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DailyCompletion entities.
func (c *DailyCompletionClient) CreateBulk(builders ...*DailyCompletionCreate) *DailyCompletionCreateBulk {
	return &DailyCompletionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DailyCompletionClient) MapCreateBulk(slice any, setFunc func(*DailyCompletionCreate, int)) *DailyCompletionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DailyCompletionCreateBulk{err: fmt.Errorf("calling to DailyCompletionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DailyCompletionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DailyCompletionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DailyCompletion.
func (c *DailyCompletionClient) Update() *DailyCompletionUpdate {
	mutation := newDailyCompletionMutation(c.config, OpUpdate)
	return &DailyCompletionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DailyCompletionClient) UpdateOne(_m *DailyCompletion) *DailyCompletionUpdateOne {
	mutation := newDailyCompletionMutation(c.config, OpUpdateOne, withDailyCompletion(_m))
	return &DailyCompletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DailyCompletionClient) UpdateOneID(id uuid.UUID) *DailyCompletionUpdateOne {
	mutation := newDailyCompletionMutation(c.config, OpUpdateOne, withDailyCompletionID(id))
	return &DailyCompletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DailyCompletion.
func (c *DailyCompletionClient) Delete() *DailyCompletionDelete {
	mutation := newDailyCompletionMutation(c.config, OpDelete)
	return &DailyCompletionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DailyCompletionClient) DeleteOne(_m *DailyCompletion) *DailyCompletionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DailyCompletionClient) DeleteOneID(id uuid.UUID) *DailyCompletionDeleteOne {
	builder := c.Delete().Where(dailycompletion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DailyCompletionDeleteOne{builder}
}

// Query returns a query builder for DailyCompletion.
func (c *DailyCompletionClient) Query() *DailyCompletionQuery {
	return &DailyCompletionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDailyCompletion},
		inters: c.Interceptors(),
	}
}

// Get returns a DailyCompletion entity by its id.
func (c *DailyCompletionClient) Get(ctx context.Context, id uuid.UUID) (*DailyCompletion, error) {
	return c.Query().Where(dailycompletion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DailyCompletionClient) GetX(ctx context.Context, id uuid.UUID) *DailyCompletion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DailyCompletionClient) Hooks() []Hook {
	return c.hooks.DailyCompletion
}

// Interceptors returns the client interceptors.
func (c *DailyCompletionClient) Interceptors() []Interceptor {
	return c.inters.DailyCompletion
}

func (c *DailyCompletionClient) mutate(ctx context.Context, m *DailyCompletionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DailyCompletionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DailyCompletionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DailyCompletionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DailyCompletionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DailyCompletion mutation op: %q", m.Op())
	}
}

// DailyLogClient is a client for the DailyLog schema.
type DailyLogClient struct {
	config
}

// NewDailyLogClient returns a client for the DailyLog from the given config.
func NewDailyLogClient(c config) *DailyLogClient {
	return &DailyLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dailylog.Hooks(f(g(h())))`.
func (c *DailyLogClient) Use(hooks ...Hook) {
	c.hooks.DailyLog = append(c.hooks.DailyLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dailylog.Intercept(f(g(h())))`.
func (c *DailyLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.DailyLog = append(c.inters.DailyLog, interceptors...)
}

// Create returns a builder for creating a DailyLog entity.
func (c *DailyLogClient) Create() *DailyLogCreate {
	mutation := newDailyLogMutation(c.config, OpCreate)
	return &DailyLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DailyLog entities.
func (c *DailyLogClient) CreateBulk(builders ...*DailyLogCreate) *DailyLogCreateBulk {
	return &DailyLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DailyLogClient) MapCreateBulk(slice any, setFunc func(*DailyLogCreate, int)) *DailyLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DailyLogCreateBulk{err: fmt.Errorf("calling to DailyLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DailyLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DailyLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DailyLog.
func (c *DailyLogClient) Update() *DailyLogUpdate {
	mutation := newDailyLogMutation(c.config, OpUpdate)
	return &DailyLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DailyLogClient) UpdateOne(_m *DailyLog) *DailyLogUpdateOne {
	mutation := newDailyLogMutation(c.config, OpUpdateOne, withDailyLog(_m))
	return &DailyLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DailyLogClient) UpdateOneID(id uuid.UUID) *DailyLogUpdateOne {
	mutation := newDailyLogMutation(c.config, OpUpdateOne, withDailyLogID(id))
	return &DailyLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DailyLog.
func (c *DailyLogClient) Delete() *DailyLogDelete {
	mutation := newDailyLogMutation(c.config, OpDelete)
	return &DailyLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DailyLogClient) DeleteOne(_m *DailyLog) *DailyLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DailyLogClient) DeleteOneID(id uuid.UUID) *DailyLogDeleteOne {
	builder := c.Delete().Where(dailylog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DailyLogDeleteOne{builder}
}

// Query returns a query builder for DailyLog.
func (c *DailyLogClient) Query() *DailyLogQuery {
	return &DailyLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDailyLog},
		inters: c.Interceptors(),
	}
}

// Get returns a DailyLog entity by its id.
func (c *DailyLogClient) Get(ctx context.Context, id uuid.UUID) (*DailyLog, error) {
	return c.Query().Where(dailylog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DailyLogClient) GetX(ctx context.Context, id uuid.UUID) *DailyLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DailyLogClient) Hooks() []Hook {
	return c.hooks.DailyLog
}

// Interceptors returns the client interceptors.
func (c *DailyLogClient) Interceptors() []Interceptor {
	return c.inters.DailyLog
}

func (c *DailyLogClient) mutate(ctx context.Context, m *DailyLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DailyLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DailyLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DailyLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DailyLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DailyLog mutation op: %q", m.Op())
	}
}

// FocusSessionClient is a client for the FocusSession schema.
type FocusSessionClient struct {
	config
}

// NewFocusSessionClient returns a client for the FocusSession from the given config.
func NewFocusSessionClient(c config) *FocusSessionClient {
	return &FocusSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `focussession.Hooks(f(g(h())))`.
func (c *FocusSessionClient) Use(hooks ...Hook) {
	c.hooks.FocusSession = append(c.hooks.FocusSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `focussession.Intercept(f(g(h())))`.
func (c *FocusSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.FocusSession = append(c.inters.FocusSession, interceptors...)
}

// Create returns a builder for creating a FocusSession entity.
func (c *FocusSessionClient) Create() *FocusSessionCreate {
	mutation := newFocusSessionMutation(c.config, OpCreate)
	return &FocusSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FocusSession entities.
func (c *FocusSessionClient) CreateBulk(builders ...*FocusSessionCreate) *FocusSessionCreateBulk {
	return &FocusSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FocusSessionClient) MapCreateBulk(slice any, setFunc func(*FocusSessionCreate, int)) *FocusSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FocusSessionCreateBulk{err: fmt.Errorf("calling to FocusSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FocusSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FocusSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FocusSession.
func (c *FocusSessionClient) Update() *FocusSessionUpdate {
	mutation := newFocusSessionMutation(c.config, OpUpdate)
	return &FocusSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FocusSessionClient) UpdateOne(_m *FocusSession) *FocusSessionUpdateOne {
	mutation := newFocusSessionMutation(c.config, OpUpdateOne, withFocusSession(_m))
	return &FocusSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FocusSessionClient) UpdateOneID(id uuid.UUID) *FocusSessionUpdateOne {
	mutation := newFocusSessionMutation(c.config, OpUpdateOne, withFocusSessionID(id))
	return &FocusSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FocusSession.
func (c *FocusSessionClient) Delete() *FocusSessionDelete {
	mutation := newFocusSessionMutation(c.config, OpDelete)
	return &FocusSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FocusSessionClient) DeleteOne(_m *FocusSession) *FocusSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FocusSessionClient) DeleteOneID(id uuid.UUID) *FocusSessionDeleteOne {
	builder := c.Delete().Where(focussession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FocusSessionDeleteOne{builder}
}

// Query returns a query builder for FocusSession.
func (c *FocusSessionClient) Query() *FocusSessionQuery {
	return &FocusSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFocusSession},
		inters: c.Interceptors(),
	}
}

// Get returns a FocusSession entity by its id.
func (c *FocusSessionClient) Get(ctx context.Context, id uuid.UUID) (*FocusSession, error) {
	return c.Query().Where(focussession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FocusSessionClient) GetX(ctx context.Context, id uuid.UUID) *FocusSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FocusSessionClient) Hooks() []Hook {
	return c.hooks.FocusSession
}

// Interceptors returns the client interceptors.
func (c *FocusSessionClient) Interceptors() []Interceptor {
	return c.inters.FocusSession
}

func (c *FocusSessionClient) mutate(ctx context.Context, m *FocusSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FocusSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FocusSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FocusSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FocusSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FocusSession mutation op: %q", m.Op())
	}
}

// HabitClient is a client for the Habit schema.
type HabitClient struct {
	config
}

// NewHabitClient returns a client for the Habit from the given config.
func NewHabitClient(c config) *HabitClient {
	return &HabitClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `habit.Hooks(f(g(h())))`.
func (c *HabitClient) Use(hooks ...Hook) {
	c.hooks.Habit = append(c.hooks.Habit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `habit.Intercept(f(g(h())))`.
func (c *HabitClient) Intercept(interceptors ...Interceptor) {
	c.inters.Habit = append(c.inters.Habit, interceptors...)
}

// Create returns a builder for creating a Habit entity.
func (c *HabitClient) Create() *HabitCreate {
	mutation := newHabitMutation(c.config, OpCreate)
	return &HabitCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Habit entities.
func (c *HabitClient) CreateBulk(builders ...*HabitCreate) *HabitCreateBulk {
	return &HabitCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HabitClient) MapCreateBulk(slice any, setFunc func(*HabitCreate, int)) *HabitCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HabitCreateBulk{err: fmt.Errorf("calling to HabitClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HabitCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HabitCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Habit.
func (c *HabitClient) Update() *HabitUpdate {
	mutation := newHabitMutation(c.config, OpUpdate)
	return &HabitUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HabitClient) UpdateOne(_m *Habit) *HabitUpdateOne {
	mutation := newHabitMutation(c.config, OpUpdateOne, withHabit(_m))
	return &HabitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HabitClient) UpdateOneID(id uuid.UUID) *HabitUpdateOne {
	mutation := newHabitMutation(c.config, OpUpdateOne, withHabitID(id))
	return &HabitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Habit.
func (c *HabitClient) Delete() *HabitDelete {
	mutation := newHabitMutation(c.config, OpDelete)
	return &HabitDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HabitClient) DeleteOne(_m *Habit) *HabitDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HabitClient) DeleteOneID(id uuid.UUID) *HabitDeleteOne {
	builder := c.Delete().Where(habit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HabitDeleteOne{builder}
}

// Query returns a query builder for Habit.
func (c *HabitClient) Query() *HabitQuery {
	return &HabitQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHabit},
		inters: c.Interceptors(),
	}
}

// Get returns a Habit entity by its id.
func (c *HabitClient) Get(ctx context.Context, id uuid.UUID) (*Habit, error) {
	return c.Query().Where(habit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HabitClient) GetX(ctx context.Context, id uuid.UUID) *Habit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HabitClient) Hooks() []Hook {
	return c.hooks.Habit
}

// Interceptors returns the client interceptors.
func (c *HabitClient) Interceptors() []Interceptor {
	return c.inters.Habit
}

func (c *HabitClient) mutate(ctx context.Context, m *HabitMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HabitCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HabitUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HabitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HabitDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Habit mutation op: %q", m.Op())
	}
}

// MicroActionClient is a client for the MicroAction schema.
type MicroActionClient struct {
	config
}

// NewMicroActionClient returns a client for the MicroAction from the given config.
func NewMicroActionClient(c config) *MicroActionClient {
	return &MicroActionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `microaction.Hooks(f(g(h())))`.
func (c *MicroActionClient) Use(hooks ...Hook) {
	c.hooks.MicroAction = append(c.hooks.MicroAction, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `microaction.Intercept(f(g(h())))`.
func (c *MicroActionClient) Intercept(interceptors ...Interceptor) {
	c.inters.MicroAction = append(c.inters.MicroAction, interceptors...)
}

// Create returns a builder for creating a MicroAction entity.
func (c *MicroActionClient) Create() *MicroActionCreate {
	mutation := newMicroActionMutation(c.config, OpCreate)
	return &MicroActionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MicroAction entities.
func (c *MicroActionClient) CreateBulk(builders ...*MicroActionCreate) *MicroActionCreateBulk {
	return &MicroActionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MicroActionClient) MapCreateBulk(slice any, setFunc func(*MicroActionCreate, int)) *MicroActionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MicroActionCreateBulk{err: fmt.Errorf("calling to MicroActionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MicroActionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MicroActionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MicroAction.
func (c *MicroActionClient) Update() *MicroActionUpdate {
	mutation := newMicroActionMutation(c.config, OpUpdate)
	return &MicroActionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MicroActionClient) UpdateOne(_m *MicroAction) *MicroActionUpdateOne {
	mutation := newMicroActionMutation(c.config, OpUpdateOne, withMicroAction(_m))
	return &MicroActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MicroActionClient) UpdateOneID(id uuid.UUID) *MicroActionUpdateOne {
	mutation := newMicroActionMutation(c.config, OpUpdateOne, withMicroActionID(id))
	return &MicroActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MicroAction.
func (c *MicroActionClient) Delete() *MicroActionDelete {
	mutation := newMicroActionMutation(c.config, OpDelete)
	return &MicroActionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MicroActionClient) DeleteOne(_m *MicroAction) *MicroActionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MicroActionClient) DeleteOneID(id uuid.UUID) *MicroActionDeleteOne {
	builder := c.Delete().Where(microaction.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MicroActionDeleteOne{builder}
}

// Query returns a query builder for MicroAction.
func (c *MicroActionClient) Query() *MicroActionQuery {
	return &MicroActionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMicroAction},
		inters: c.Interceptors(),
	}
}

// Get returns a MicroAction entity by its id.
func (c *MicroActionClient) Get(ctx context.Context, id uuid.UUID) (*MicroAction, error) {
	return c.Query().Where(microaction.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MicroActionClient) GetX(ctx context.Context, id uuid.UUID) *MicroAction {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MicroActionClient) Hooks() []Hook {
	return c.hooks.MicroAction
}

// Interceptors returns the client interceptors.
func (c *MicroActionClient) Interceptors() []Interceptor {
	return c.inters.MicroAction
}

func (c *MicroActionClient) mutate(ctx context.Context, m *MicroActionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MicroActionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MicroActionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MicroActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MicroActionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MicroAction mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserCharacterConfigClient is a client for the UserCharacterConfig schema.
type UserCharacterConfigClient struct {
	config
}

// NewUserCharacterConfigClient returns a client for the UserCharacterConfig from the given config.
func NewUserCharacterConfigClient(c config) *UserCharacterConfigClient {
	return &UserCharacterConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usercharacterconfig.Hooks(f(g(h())))`.
func (c *UserCharacterConfigClient) Use(hooks ...Hook) {
	c.hooks.UserCharacterConfig = append(c.hooks.UserCharacterConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usercharacterconfig.Intercept(f(g(h())))`.
func (c *UserCharacterConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserCharacterConfig = append(c.inters.UserCharacterConfig, interceptors...)
}

// Create returns a builder for creating a UserCharacterConfig entity.
func (c *UserCharacterConfigClient) Create() *UserCharacterConfigCreate {
	mutation := newUserCharacterConfigMutation(c.config, OpCreate)
	return &UserCharacterConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserCharacterConfig entities.
func (c *UserCharacterConfigClient) CreateBulk(builders ...*UserCharacterConfigCreate) *UserCharacterConfigCreateBulk {
	return &UserCharacterConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserCharacterConfigClient) MapCreateBulk(slice any, setFunc func(*UserCharacterConfigCreate, int)) *UserCharacterConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCharacterConfigCreateBulk{err: fmt.Errorf("calling to UserCharacterConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCharacterConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCharacterConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserCharacterConfig.
func (c *UserCharacterConfigClient) Update() *UserCharacterConfigUpdate {
	mutation := newUserCharacterConfigMutation(c.config, OpUpdate)
	return &UserCharacterConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserCharacterConfigClient) UpdateOne(_m *UserCharacterConfig) *UserCharacterConfigUpdateOne {
	mutation := newUserCharacterConfigMutation(c.config, OpUpdateOne, withUserCharacterConfig(_m))
	return &UserCharacterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserCharacterConfigClient) UpdateOneID(id uuid.UUID) *UserCharacterConfigUpdateOne {
	mutation := newUserCharacterConfigMutation(c.config, OpUpdateOne, withUserCharacterConfigID(id))
	return &UserCharacterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserCharacterConfig.
func (c *UserCharacterConfigClient) Delete() *UserCharacterConfigDelete {
	mutation := newUserCharacterConfigMutation(c.config, OpDelete)
	return &UserCharacterConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserCharacterConfigClient) DeleteOne(_m *UserCharacterConfig) *UserCharacterConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserCharacterConfigClient) DeleteOneID(id uuid.UUID) *UserCharacterConfigDeleteOne {
	builder := c.Delete().Where(usercharacterconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserCharacterConfigDeleteOne{builder}
}

// Query returns a query builder for UserCharacterConfig.
func (c *UserCharacterConfigClient) Query() *UserCharacterConfigQuery {
	return &UserCharacterConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserCharacterConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a UserCharacterConfig entity by its id.
func (c *UserCharacterConfigClient) Get(ctx context.Context, id uuid.UUID) (*UserCharacterConfig, error) {
	return c.Query().Where(usercharacterconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserCharacterConfigClient) GetX(ctx context.Context, id uuid.UUID) *UserCharacterConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserCharacterConfigClient) Hooks() []Hook {
	return c.hooks.UserCharacterConfig
}

// Interceptors returns the client interceptors.
func (c *UserCharacterConfigClient) Interceptors() []Interceptor {
	return c.inters.UserCharacterConfig
}

func (c *UserCharacterConfigClient) mutate(ctx context.Context, m *UserCharacterConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCharacterConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserCharacterConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserCharacterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserCharacterConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserCharacterConfig mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CelebrityCharacter, ChatMessage, CompanionConfig, DailyCompletion, DailyLog,
		FocusSession, Habit, MicroAction, User, UserCharacterConfig []ent.Hook
	}
	inters struct {
		CelebrityCharacter, ChatMessage, CompanionConfig, DailyCompletion, DailyLog,
		FocusSession, Habit, MicroAction, User, UserCharacterConfig []ent.Interceptor
	}
)
