// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/companionconfig"
)

// CompanionConfig is the model entity for the CompanionConfig schema.
type CompanionConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AvatarType holds the value of the "avatar_type" field.
	AvatarType string `json:"avatar_type,omitempty"`
	// PersonalityType holds the value of the "personality_type" field.
	PersonalityType string `json:"personality_type,omitempty"`
	// EncouragementStyle holds the value of the "encouragement_style" field.
	EncouragementStyle string `json:"encouragement_style,omitempty"`
	// VoiceType holds the value of the "voice_type" field.
	VoiceType *string `json:"voice_type,omitempty"`
	// GrowthLevel holds the value of the "growth_level" field.
	GrowthLevel int `json:"growth_level,omitempty"`
	// RelationshipScore holds the value of the "relationship_score" field.
	RelationshipScore float64 `json:"relationship_score,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID *string `json:"character_id,omitempty"`
	// CustomName holds the value of the "custom_name" field.
	CustomName *string `json:"custom_name,omitempty"`
	// CustomAvatarURL holds the value of the "custom_avatar_url" field.
	CustomAvatarURL *string `json:"custom_avatar_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompanionConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case companionconfig.FieldRelationshipScore:
			values[i] = new(sql.NullFloat64)
		case companionconfig.FieldGrowthLevel:
			values[i] = new(sql.NullInt64)
		case companionconfig.FieldName, companionconfig.FieldAvatarType, companionconfig.FieldPersonalityType, companionconfig.FieldEncouragementStyle, companionconfig.FieldVoiceType, companionconfig.FieldCharacterID, companionconfig.FieldCustomName, companionconfig.FieldCustomAvatarURL:
			values[i] = new(sql.NullString)
		case companionconfig.FieldCreatedAt, companionconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case companionconfig.FieldID, companionconfig.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompanionConfig fields.
func (_m *CompanionConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case companionconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case companionconfig.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case companionconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case companionconfig.FieldAvatarType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_type", values[i])
			} else if value.Valid {
				_m.AvatarType = value.String
			}
		case companionconfig.FieldPersonalityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field personality_type", values[i])
			} else if value.Valid {
				_m.PersonalityType = value.String
			}
		case companionconfig.FieldEncouragementStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encouragement_style", values[i])
			} else if value.Valid {
				_m.EncouragementStyle = value.String
			}
		case companionconfig.FieldVoiceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field voice_type", values[i])
			} else if value.Valid {
				_m.VoiceType = new(string)
				*_m.VoiceType = value.String
			}
		case companionconfig.FieldGrowthLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field growth_level", values[i])
			} else if value.Valid {
				_m.GrowthLevel = int(value.Int64)
			}
		case companionconfig.FieldRelationshipScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field relationship_score", values[i])
			} else if value.Valid {
				_m.RelationshipScore = value.Float64
			}
		case companionconfig.FieldCharacterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = new(string)
				*_m.CharacterID = value.String
			}
		case companionconfig.FieldCustomName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_name", values[i])
			} else if value.Valid {
				_m.CustomName = new(string)
				*_m.CustomName = value.String
			}
		case companionconfig.FieldCustomAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_avatar_url", values[i])
			} else if value.Valid {
				_m.CustomAvatarURL = new(string)
				*_m.CustomAvatarURL = value.String
			}
		case companionconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case companionconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompanionConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CompanionConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CompanionConfig.
// Note that you need to call CompanionConfig.Unwrap() before calling this method if this CompanionConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompanionConfig) Update() *CompanionConfigUpdateOne {
	return NewCompanionConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompanionConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompanionConfig) Unwrap() *CompanionConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompanionConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompanionConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CompanionConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("avatar_type=")
	builder.WriteString(_m.AvatarType)
	builder.WriteString(", ")
	builder.WriteString("personality_type=")
	builder.WriteString(_m.PersonalityType)
	builder.WriteString(", ")
	builder.WriteString("encouragement_style=")
	builder.WriteString(_m.EncouragementStyle)
	builder.WriteString(", ")
	if v := _m.VoiceType; v != nil {
		builder.WriteString("voice_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("growth_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrowthLevel))
	builder.WriteString(", ")
	builder.WriteString("relationship_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelationshipScore))
	builder.WriteString(", ")
	if v := _m.CharacterID; v != nil {
		builder.WriteString("character_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomName; v != nil {
		builder.WriteString("custom_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomAvatarURL; v != nil {
		builder.WriteString("custom_avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CompanionConfigs is a parsable slice of CompanionConfig.
type CompanionConfigs []*CompanionConfig
