// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lagom/lagom-server/ent/companionconfig"
	"github.com/lagom/lagom-server/ent/predicate"
)

// CompanionConfigDelete is the builder for deleting a CompanionConfig entity.
type CompanionConfigDelete struct {
	config
	hooks    []Hook
	mutation *CompanionConfigMutation
}

// Where appends a list predicates to the CompanionConfigDelete builder.
func (_d *CompanionConfigDelete) Where(ps ...predicate.CompanionConfig) *CompanionConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CompanionConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompanionConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CompanionConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(companionconfig.Table, sqlgraph.NewFieldSpec(companionconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CompanionConfigDeleteOne is the builder for deleting a single CompanionConfig entity.
type CompanionConfigDeleteOne struct {
	_d *CompanionConfigDelete
}

// Where appends a list predicates to the CompanionConfigDelete builder.
func (_d *CompanionConfigDeleteOne) Where(ps ...predicate.CompanionConfig) *CompanionConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CompanionConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{companionconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompanionConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
