// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/companionconfig"
)

// CompanionConfigCreate is the builder for creating a CompanionConfig entity.
type CompanionConfigCreate struct {
	config
	mutation *CompanionConfigMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *CompanionConfigCreate) SetUserID(v uuid.UUID) *CompanionConfigCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CompanionConfigCreate) SetName(v string) *CompanionConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableName(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetAvatarType sets the "avatar_type" field.
func (_c *CompanionConfigCreate) SetAvatarType(v string) *CompanionConfigCreate {
	_c.mutation.SetAvatarType(v)
	return _c
}

// SetNillableAvatarType sets the "avatar_type" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableAvatarType(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetAvatarType(*v)
	}
	return _c
}

// SetPersonalityType sets the "personality_type" field.
func (_c *CompanionConfigCreate) SetPersonalityType(v string) *CompanionConfigCreate {
	_c.mutation.SetPersonalityType(v)
	return _c
}

// SetNillablePersonalityType sets the "personality_type" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillablePersonalityType(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetPersonalityType(*v)
	}
	return _c
}

// SetEncouragementStyle sets the "encouragement_style" field.
func (_c *CompanionConfigCreate) SetEncouragementStyle(v string) *CompanionConfigCreate {
	_c.mutation.SetEncouragementStyle(v)
	return _c
}

// SetNillableEncouragementStyle sets the "encouragement_style" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableEncouragementStyle(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetEncouragementStyle(*v)
	}
	return _c
}

// SetVoiceType sets the "voice_type" field.
func (_c *CompanionConfigCreate) SetVoiceType(v string) *CompanionConfigCreate {
	_c.mutation.SetVoiceType(v)
	return _c
}

// SetNillableVoiceType sets the "voice_type" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableVoiceType(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetVoiceType(*v)
	}
	return _c
}

// SetGrowthLevel sets the "growth_level" field.
func (_c *CompanionConfigCreate) SetGrowthLevel(v int) *CompanionConfigCreate {
	_c.mutation.SetGrowthLevel(v)
	return _c
}

// SetNillableGrowthLevel sets the "growth_level" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableGrowthLevel(v *int) *CompanionConfigCreate {
	if v != nil {
		_c.SetGrowthLevel(*v)
	}
	return _c
}

// SetRelationshipScore sets the "relationship_score" field.
func (_c *CompanionConfigCreate) SetRelationshipScore(v float64) *CompanionConfigCreate {
	_c.mutation.SetRelationshipScore(v)
	return _c
}

// SetNillableRelationshipScore sets the "relationship_score" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableRelationshipScore(v *float64) *CompanionConfigCreate {
	if v != nil {
		_c.SetRelationshipScore(*v)
	}
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *CompanionConfigCreate) SetCharacterID(v string) *CompanionConfigCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableCharacterID(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetCharacterID(*v)
	}
	return _c
}

// SetCustomName sets the "custom_name" field.
func (_c *CompanionConfigCreate) SetCustomName(v string) *CompanionConfigCreate {
	_c.mutation.SetCustomName(v)
	return _c
}

// SetNillableCustomName sets the "custom_name" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableCustomName(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetCustomName(*v)
	}
	return _c
}

// SetCustomAvatarURL sets the "custom_avatar_url" field.
func (_c *CompanionConfigCreate) SetCustomAvatarURL(v string) *CompanionConfigCreate {
	_c.mutation.SetCustomAvatarURL(v)
	return _c
}

// SetNillableCustomAvatarURL sets the "custom_avatar_url" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableCustomAvatarURL(v *string) *CompanionConfigCreate {
	if v != nil {
		_c.SetCustomAvatarURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CompanionConfigCreate) SetCreatedAt(v time.Time) *CompanionConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableCreatedAt(v *time.Time) *CompanionConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CompanionConfigCreate) SetUpdatedAt(v time.Time) *CompanionConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableUpdatedAt(v *time.Time) *CompanionConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CompanionConfigCreate) SetID(v uuid.UUID) *CompanionConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CompanionConfigCreate) SetNillableID(v *uuid.UUID) *CompanionConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CompanionConfigMutation object of the builder.
func (_c *CompanionConfigCreate) Mutation() *CompanionConfigMutation {
	return _c.mutation
}

// Save creates the CompanionConfig in the database.
func (_c *CompanionConfigCreate) Save(ctx context.Context) (*CompanionConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompanionConfigCreate) SaveX(ctx context.Context) *CompanionConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompanionConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompanionConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompanionConfigCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := companionconfig.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.AvatarType(); !ok {
		v := companionconfig.DefaultAvatarType
		_c.mutation.SetAvatarType(v)
	}
	if _, ok := _c.mutation.PersonalityType(); !ok {
		v := companionconfig.DefaultPersonalityType
		_c.mutation.SetPersonalityType(v)
	}
	if _, ok := _c.mutation.EncouragementStyle(); !ok {
		v := companionconfig.DefaultEncouragementStyle
		_c.mutation.SetEncouragementStyle(v)
	}
	if _, ok := _c.mutation.GrowthLevel(); !ok {
		v := companionconfig.DefaultGrowthLevel
		_c.mutation.SetGrowthLevel(v)
	}
	if _, ok := _c.mutation.RelationshipScore(); !ok {
		v := companionconfig.DefaultRelationshipScore
		_c.mutation.SetRelationshipScore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := companionconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := companionconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := companionconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompanionConfigCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CompanionConfig.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CompanionConfig.name"`)}
	}
	if _, ok := _c.mutation.AvatarType(); !ok {
		return &ValidationError{Name: "avatar_type", err: errors.New(`ent: missing required field "CompanionConfig.avatar_type"`)}
	}
	if _, ok := _c.mutation.PersonalityType(); !ok {
		return &ValidationError{Name: "personality_type", err: errors.New(`ent: missing required field "CompanionConfig.personality_type"`)}
	}
	if _, ok := _c.mutation.EncouragementStyle(); !ok {
		return &ValidationError{Name: "encouragement_style", err: errors.New(`ent: missing required field "CompanionConfig.encouragement_style"`)}
	}
	if _, ok := _c.mutation.GrowthLevel(); !ok {
		return &ValidationError{Name: "growth_level", err: errors.New(`ent: missing required field "CompanionConfig.growth_level"`)}
	}
	if _, ok := _c.mutation.RelationshipScore(); !ok {
		return &ValidationError{Name: "relationship_score", err: errors.New(`ent: missing required field "CompanionConfig.relationship_score"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CompanionConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CompanionConfig.updated_at"`)}
	}
	return nil
}

func (_c *CompanionConfigCreate) sqlSave(ctx context.Context) (*CompanionConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompanionConfigCreate) createSpec() (*CompanionConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CompanionConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(companionconfig.Table, sqlgraph.NewFieldSpec(companionconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(companionconfig.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(companionconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AvatarType(); ok {
		_spec.SetField(companionconfig.FieldAvatarType, field.TypeString, value)
		_node.AvatarType = value
	}
	if value, ok := _c.mutation.PersonalityType(); ok {
		_spec.SetField(companionconfig.FieldPersonalityType, field.TypeString, value)
		_node.PersonalityType = value
	}
	if value, ok := _c.mutation.EncouragementStyle(); ok {
		_spec.SetField(companionconfig.FieldEncouragementStyle, field.TypeString, value)
		_node.EncouragementStyle = value
	}
	if value, ok := _c.mutation.VoiceType(); ok {
		_spec.SetField(companionconfig.FieldVoiceType, field.TypeString, value)
		_node.VoiceType = &value
	}
	if value, ok := _c.mutation.GrowthLevel(); ok {
		_spec.SetField(companionconfig.FieldGrowthLevel, field.TypeInt, value)
		_node.GrowthLevel = value
	}
	if value, ok := _c.mutation.RelationshipScore(); ok {
		_spec.SetField(companionconfig.FieldRelationshipScore, field.TypeFloat64, value)
		_node.RelationshipScore = value
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(companionconfig.FieldCharacterID, field.TypeString, value)
		_node.CharacterID = &value
	}
	if value, ok := _c.mutation.CustomName(); ok {
		_spec.SetField(companionconfig.FieldCustomName, field.TypeString, value)
		_node.CustomName = &value
	}
	if value, ok := _c.mutation.CustomAvatarURL(); ok {
		_spec.SetField(companionconfig.FieldCustomAvatarURL, field.TypeString, value)
		_node.CustomAvatarURL = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(companionconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(companionconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CompanionConfigCreateBulk is the builder for creating many CompanionConfig entities in bulk.
type CompanionConfigCreateBulk struct {
	config
	err      error
	builders []*CompanionConfigCreate
}

// Save creates the CompanionConfig entities in the database.
func (_c *CompanionConfigCreateBulk) Save(ctx context.Context) ([]*CompanionConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CompanionConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompanionConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompanionConfigCreateBulk) SaveX(ctx context.Context) []*CompanionConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompanionConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompanionConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
