// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/companionconfig"
	"github.com/lagom/lagom-server/ent/predicate"
)

// CompanionConfigUpdate is the builder for updating CompanionConfig entities.
type CompanionConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *CompanionConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CompanionConfigUpdate builder.
func (_u *CompanionConfigUpdate) Where(ps ...predicate.CompanionConfig) *CompanionConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CompanionConfigUpdate) SetUserID(v uuid.UUID) *CompanionConfigUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableUserID(v *uuid.UUID) *CompanionConfigUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CompanionConfigUpdate) SetName(v string) *CompanionConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableName(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarType sets the "avatar_type" field.
func (_u *CompanionConfigUpdate) SetAvatarType(v string) *CompanionConfigUpdate {
	_u.mutation.SetAvatarType(v)
	return _u
}

// SetNillableAvatarType sets the "avatar_type" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableAvatarType(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetAvatarType(*v)
	}
	return _u
}

// SetPersonalityType sets the "personality_type" field.
func (_u *CompanionConfigUpdate) SetPersonalityType(v string) *CompanionConfigUpdate {
	_u.mutation.SetPersonalityType(v)
	return _u
}

// SetNillablePersonalityType sets the "personality_type" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillablePersonalityType(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetPersonalityType(*v)
	}
	return _u
}

// SetEncouragementStyle sets the "encouragement_style" field.
func (_u *CompanionConfigUpdate) SetEncouragementStyle(v string) *CompanionConfigUpdate {
	_u.mutation.SetEncouragementStyle(v)
	return _u
}

// SetNillableEncouragementStyle sets the "encouragement_style" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableEncouragementStyle(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetEncouragementStyle(*v)
	}
	return _u
}

// SetVoiceType sets the "voice_type" field.
func (_u *CompanionConfigUpdate) SetVoiceType(v string) *CompanionConfigUpdate {
	_u.mutation.SetVoiceType(v)
	return _u
}

// SetNillableVoiceType sets the "voice_type" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableVoiceType(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetVoiceType(*v)
	}
	return _u
}

// ClearVoiceType clears the value of the "voice_type" field.
func (_u *CompanionConfigUpdate) ClearVoiceType() *CompanionConfigUpdate {
	_u.mutation.ClearVoiceType()
	return _u
}

// SetGrowthLevel sets the "growth_level" field.
func (_u *CompanionConfigUpdate) SetGrowthLevel(v int) *CompanionConfigUpdate {
	_u.mutation.ResetGrowthLevel()
	_u.mutation.SetGrowthLevel(v)
	return _u
}

// SetNillableGrowthLevel sets the "growth_level" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableGrowthLevel(v *int) *CompanionConfigUpdate {
	if v != nil {
		_u.SetGrowthLevel(*v)
	}
	return _u
}

// AddGrowthLevel adds value to the "growth_level" field.
func (_u *CompanionConfigUpdate) AddGrowthLevel(v int) *CompanionConfigUpdate {
	_u.mutation.AddGrowthLevel(v)
	return _u
}

// SetRelationshipScore sets the "relationship_score" field.
func (_u *CompanionConfigUpdate) SetRelationshipScore(v float64) *CompanionConfigUpdate {
	_u.mutation.ResetRelationshipScore()
	_u.mutation.SetRelationshipScore(v)
	return _u
}

// SetNillableRelationshipScore sets the "relationship_score" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableRelationshipScore(v *float64) *CompanionConfigUpdate {
	if v != nil {
		_u.SetRelationshipScore(*v)
	}
	return _u
}

// AddRelationshipScore adds value to the "relationship_score" field.
func (_u *CompanionConfigUpdate) AddRelationshipScore(v float64) *CompanionConfigUpdate {
	_u.mutation.AddRelationshipScore(v)
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CompanionConfigUpdate) SetCharacterID(v string) *CompanionConfigUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableCharacterID(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *CompanionConfigUpdate) ClearCharacterID() *CompanionConfigUpdate {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetCustomName sets the "custom_name" field.
func (_u *CompanionConfigUpdate) SetCustomName(v string) *CompanionConfigUpdate {
	_u.mutation.SetCustomName(v)
	return _u
}

// SetNillableCustomName sets the "custom_name" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableCustomName(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetCustomName(*v)
	}
	return _u
}

// ClearCustomName clears the value of the "custom_name" field.
func (_u *CompanionConfigUpdate) ClearCustomName() *CompanionConfigUpdate {
	_u.mutation.ClearCustomName()
	return _u
}

// SetCustomAvatarURL sets the "custom_avatar_url" field.
func (_u *CompanionConfigUpdate) SetCustomAvatarURL(v string) *CompanionConfigUpdate {
	_u.mutation.SetCustomAvatarURL(v)
	return _u
}

// SetNillableCustomAvatarURL sets the "custom_avatar_url" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableCustomAvatarURL(v *string) *CompanionConfigUpdate {
	if v != nil {
		_u.SetCustomAvatarURL(*v)
	}
	return _u
}

// ClearCustomAvatarURL clears the value of the "custom_avatar_url" field.
func (_u *CompanionConfigUpdate) ClearCustomAvatarURL() *CompanionConfigUpdate {
	_u.mutation.ClearCustomAvatarURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CompanionConfigUpdate) SetCreatedAt(v time.Time) *CompanionConfigUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CompanionConfigUpdate) SetNillableCreatedAt(v *time.Time) *CompanionConfigUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompanionConfigUpdate) SetUpdatedAt(v time.Time) *CompanionConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CompanionConfigMutation object of the builder.
func (_u *CompanionConfigUpdate) Mutation() *CompanionConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompanionConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanionConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompanionConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanionConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompanionConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := companionconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CompanionConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompanionConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CompanionConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(companionconfig.Table, companionconfig.Columns, sqlgraph.NewFieldSpec(companionconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(companionconfig.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(companionconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarType(); ok {
		_spec.SetField(companionconfig.FieldAvatarType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PersonalityType(); ok {
		_spec.SetField(companionconfig.FieldPersonalityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncouragementStyle(); ok {
		_spec.SetField(companionconfig.FieldEncouragementStyle, field.TypeString, value)
	}
	if value, ok := _u.mutation.VoiceType(); ok {
		_spec.SetField(companionconfig.FieldVoiceType, field.TypeString, value)
	}
	if _u.mutation.VoiceTypeCleared() {
		_spec.ClearField(companionconfig.FieldVoiceType, field.TypeString)
	}
	if value, ok := _u.mutation.GrowthLevel(); ok {
		_spec.SetField(companionconfig.FieldGrowthLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGrowthLevel(); ok {
		_spec.AddField(companionconfig.FieldGrowthLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RelationshipScore(); ok {
		_spec.SetField(companionconfig.FieldRelationshipScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRelationshipScore(); ok {
		_spec.AddField(companionconfig.FieldRelationshipScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(companionconfig.FieldCharacterID, field.TypeString, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(companionconfig.FieldCharacterID, field.TypeString)
	}
	if value, ok := _u.mutation.CustomName(); ok {
		_spec.SetField(companionconfig.FieldCustomName, field.TypeString, value)
	}
	if _u.mutation.CustomNameCleared() {
		_spec.ClearField(companionconfig.FieldCustomName, field.TypeString)
	}
	if value, ok := _u.mutation.CustomAvatarURL(); ok {
		_spec.SetField(companionconfig.FieldCustomAvatarURL, field.TypeString, value)
	}
	if _u.mutation.CustomAvatarURLCleared() {
		_spec.ClearField(companionconfig.FieldCustomAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(companionconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(companionconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{companionconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompanionConfigUpdateOne is the builder for updating a single CompanionConfig entity.
type CompanionConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CompanionConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *CompanionConfigUpdateOne) SetUserID(v uuid.UUID) *CompanionConfigUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableUserID(v *uuid.UUID) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CompanionConfigUpdateOne) SetName(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableName(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarType sets the "avatar_type" field.
func (_u *CompanionConfigUpdateOne) SetAvatarType(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetAvatarType(v)
	return _u
}

// SetNillableAvatarType sets the "avatar_type" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableAvatarType(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetAvatarType(*v)
	}
	return _u
}

// SetPersonalityType sets the "personality_type" field.
func (_u *CompanionConfigUpdateOne) SetPersonalityType(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetPersonalityType(v)
	return _u
}

// SetNillablePersonalityType sets the "personality_type" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillablePersonalityType(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetPersonalityType(*v)
	}
	return _u
}

// SetEncouragementStyle sets the "encouragement_style" field.
func (_u *CompanionConfigUpdateOne) SetEncouragementStyle(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetEncouragementStyle(v)
	return _u
}

// SetNillableEncouragementStyle sets the "encouragement_style" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableEncouragementStyle(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetEncouragementStyle(*v)
	}
	return _u
}

// SetVoiceType sets the "voice_type" field.
func (_u *CompanionConfigUpdateOne) SetVoiceType(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetVoiceType(v)
	return _u
}

// SetNillableVoiceType sets the "voice_type" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableVoiceType(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetVoiceType(*v)
	}
	return _u
}

// ClearVoiceType clears the value of the "voice_type" field.
func (_u *CompanionConfigUpdateOne) ClearVoiceType() *CompanionConfigUpdateOne {
	_u.mutation.ClearVoiceType()
	return _u
}

// SetGrowthLevel sets the "growth_level" field.
func (_u *CompanionConfigUpdateOne) SetGrowthLevel(v int) *CompanionConfigUpdateOne {
	_u.mutation.ResetGrowthLevel()
	_u.mutation.SetGrowthLevel(v)
	return _u
}

// SetNillableGrowthLevel sets the "growth_level" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableGrowthLevel(v *int) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetGrowthLevel(*v)
	}
	return _u
}

// AddGrowthLevel adds value to the "growth_level" field.
func (_u *CompanionConfigUpdateOne) AddGrowthLevel(v int) *CompanionConfigUpdateOne {
	_u.mutation.AddGrowthLevel(v)
	return _u
}

// SetRelationshipScore sets the "relationship_score" field.
func (_u *CompanionConfigUpdateOne) SetRelationshipScore(v float64) *CompanionConfigUpdateOne {
	_u.mutation.ResetRelationshipScore()
	_u.mutation.SetRelationshipScore(v)
	return _u
}

// SetNillableRelationshipScore sets the "relationship_score" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableRelationshipScore(v *float64) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetRelationshipScore(*v)
	}
	return _u
}

// AddRelationshipScore adds value to the "relationship_score" field.
func (_u *CompanionConfigUpdateOne) AddRelationshipScore(v float64) *CompanionConfigUpdateOne {
	_u.mutation.AddRelationshipScore(v)
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CompanionConfigUpdateOne) SetCharacterID(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableCharacterID(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *CompanionConfigUpdateOne) ClearCharacterID() *CompanionConfigUpdateOne {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetCustomName sets the "custom_name" field.
func (_u *CompanionConfigUpdateOne) SetCustomName(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetCustomName(v)
	return _u
}

// SetNillableCustomName sets the "custom_name" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableCustomName(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetCustomName(*v)
	}
	return _u
}

// ClearCustomName clears the value of the "custom_name" field.
func (_u *CompanionConfigUpdateOne) ClearCustomName() *CompanionConfigUpdateOne {
	_u.mutation.ClearCustomName()
	return _u
}

// SetCustomAvatarURL sets the "custom_avatar_url" field.
func (_u *CompanionConfigUpdateOne) SetCustomAvatarURL(v string) *CompanionConfigUpdateOne {
	_u.mutation.SetCustomAvatarURL(v)
	return _u
}

// SetNillableCustomAvatarURL sets the "custom_avatar_url" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableCustomAvatarURL(v *string) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetCustomAvatarURL(*v)
	}
	return _u
}

// ClearCustomAvatarURL clears the value of the "custom_avatar_url" field.
func (_u *CompanionConfigUpdateOne) ClearCustomAvatarURL() *CompanionConfigUpdateOne {
	_u.mutation.ClearCustomAvatarURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CompanionConfigUpdateOne) SetCreatedAt(v time.Time) *CompanionConfigUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CompanionConfigUpdateOne) SetNillableCreatedAt(v *time.Time) *CompanionConfigUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompanionConfigUpdateOne) SetUpdatedAt(v time.Time) *CompanionConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CompanionConfigMutation object of the builder.
func (_u *CompanionConfigUpdateOne) Mutation() *CompanionConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the CompanionConfigUpdate builder.
func (_u *CompanionConfigUpdateOne) Where(ps ...predicate.CompanionConfig) *CompanionConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompanionConfigUpdateOne) Select(field string, fields ...string) *CompanionConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CompanionConfig entity.
func (_u *CompanionConfigUpdateOne) Save(ctx context.Context) (*CompanionConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompanionConfigUpdateOne) SaveX(ctx context.Context) *CompanionConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompanionConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompanionConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompanionConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := companionconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CompanionConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CompanionConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CompanionConfigUpdateOne) sqlSave(ctx context.Context) (_node *CompanionConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(companionconfig.Table, companionconfig.Columns, sqlgraph.NewFieldSpec(companionconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CompanionConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, companionconfig.FieldID)
		for _, f := range fields {
			if !companionconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != companionconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(companionconfig.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(companionconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarType(); ok {
		_spec.SetField(companionconfig.FieldAvatarType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PersonalityType(); ok {
		_spec.SetField(companionconfig.FieldPersonalityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncouragementStyle(); ok {
		_spec.SetField(companionconfig.FieldEncouragementStyle, field.TypeString, value)
	}
	if value, ok := _u.mutation.VoiceType(); ok {
		_spec.SetField(companionconfig.FieldVoiceType, field.TypeString, value)
	}
	if _u.mutation.VoiceTypeCleared() {
		_spec.ClearField(companionconfig.FieldVoiceType, field.TypeString)
	}
	if value, ok := _u.mutation.GrowthLevel(); ok {
		_spec.SetField(companionconfig.FieldGrowthLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGrowthLevel(); ok {
		_spec.AddField(companionconfig.FieldGrowthLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RelationshipScore(); ok {
		_spec.SetField(companionconfig.FieldRelationshipScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRelationshipScore(); ok {
		_spec.AddField(companionconfig.FieldRelationshipScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(companionconfig.FieldCharacterID, field.TypeString, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(companionconfig.FieldCharacterID, field.TypeString)
	}
	if value, ok := _u.mutation.CustomName(); ok {
		_spec.SetField(companionconfig.FieldCustomName, field.TypeString, value)
	}
	if _u.mutation.CustomNameCleared() {
		_spec.ClearField(companionconfig.FieldCustomName, field.TypeString)
	}
	if value, ok := _u.mutation.CustomAvatarURL(); ok {
		_spec.SetField(companionconfig.FieldCustomAvatarURL, field.TypeString, value)
	}
	if _u.mutation.CustomAvatarURLCleared() {
		_spec.ClearField(companionconfig.FieldCustomAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(companionconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(companionconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CompanionConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{companionconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
