// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/dailycompletion"
)

// DailyCompletionCreate is the builder for creating a DailyCompletion entity.
type DailyCompletionCreate struct {
	config
	mutation *DailyCompletionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *DailyCompletionCreate) SetUserID(v uuid.UUID) *DailyCompletionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetHabitID sets the "habit_id" field.
func (_c *DailyCompletionCreate) SetHabitID(v uuid.UUID) *DailyCompletionCreate {
	_c.mutation.SetHabitID(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *DailyCompletionCreate) SetDate(v time.Time) *DailyCompletionCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DailyCompletionCreate) SetCompletedAt(v time.Time) *DailyCompletionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DailyCompletionCreate) SetNillableCompletedAt(v *time.Time) *DailyCompletionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetQualityScore sets the "quality_score" field.
func (_c *DailyCompletionCreate) SetQualityScore(v int) *DailyCompletionCreate {
	_c.mutation.SetQualityScore(v)
	return _c
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_c *DailyCompletionCreate) SetNillableQualityScore(v *int) *DailyCompletionCreate {
	if v != nil {
		_c.SetQualityScore(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *DailyCompletionCreate) SetNote(v string) *DailyCompletionCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *DailyCompletionCreate) SetNillableNote(v *string) *DailyCompletionCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DailyCompletionCreate) SetID(v uuid.UUID) *DailyCompletionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DailyCompletionCreate) SetNillableID(v *uuid.UUID) *DailyCompletionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DailyCompletionMutation object of the builder.
func (_c *DailyCompletionCreate) Mutation() *DailyCompletionMutation {
	return _c.mutation
}

// Save creates the DailyCompletion in the database.
func (_c *DailyCompletionCreate) Save(ctx context.Context) (*DailyCompletion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyCompletionCreate) SaveX(ctx context.Context) *DailyCompletion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyCompletionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyCompletionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyCompletionCreate) defaults() {
	if _, ok := _c.mutation.CompletedAt(); !ok {
		v := dailycompletion.DefaultCompletedAt()
		_c.mutation.SetCompletedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dailycompletion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyCompletionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DailyCompletion.user_id"`)}
	}
	if _, ok := _c.mutation.HabitID(); !ok {
		return &ValidationError{Name: "habit_id", err: errors.New(`ent: missing required field "DailyCompletion.habit_id"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "DailyCompletion.date"`)}
	}
	if _, ok := _c.mutation.CompletedAt(); !ok {
		return &ValidationError{Name: "completed_at", err: errors.New(`ent: missing required field "DailyCompletion.completed_at"`)}
	}
	return nil
}

func (_c *DailyCompletionCreate) sqlSave(ctx context.Context) (*DailyCompletion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyCompletionCreate) createSpec() (*DailyCompletion, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyCompletion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailycompletion.Table, sqlgraph.NewFieldSpec(dailycompletion.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(dailycompletion.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.HabitID(); ok {
		_spec.SetField(dailycompletion.FieldHabitID, field.TypeUUID, value)
		_node.HabitID = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(dailycompletion.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(dailycompletion.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.QualityScore(); ok {
		_spec.SetField(dailycompletion.FieldQualityScore, field.TypeInt, value)
		_node.QualityScore = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(dailycompletion.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	return _node, _spec
}

// DailyCompletionCreateBulk is the builder for creating many DailyCompletion entities in bulk.
type DailyCompletionCreateBulk struct {
	config
	err      error
	builders []*DailyCompletionCreate
}

// Save creates the DailyCompletion entities in the database.
func (_c *DailyCompletionCreateBulk) Save(ctx context.Context) ([]*DailyCompletion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyCompletion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyCompletionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyCompletionCreateBulk) SaveX(ctx context.Context) []*DailyCompletion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyCompletionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyCompletionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
