// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/dailycompletion"
	"github.com/lagom/lagom-server/ent/predicate"
)

// DailyCompletionUpdate is the builder for updating DailyCompletion entities.
type DailyCompletionUpdate struct {
	config
	hooks    []Hook
	mutation *DailyCompletionMutation
}

// Where appends a list predicates to the DailyCompletionUpdate builder.
func (_u *DailyCompletionUpdate) Where(ps ...predicate.DailyCompletion) *DailyCompletionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCompletionUpdate) SetUserID(v uuid.UUID) *DailyCompletionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableUserID(v *uuid.UUID) *DailyCompletionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetHabitID sets the "habit_id" field.
func (_u *DailyCompletionUpdate) SetHabitID(v uuid.UUID) *DailyCompletionUpdate {
	_u.mutation.SetHabitID(v)
	return _u
}

// SetNillableHabitID sets the "habit_id" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableHabitID(v *uuid.UUID) *DailyCompletionUpdate {
	if v != nil {
		_u.SetHabitID(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyCompletionUpdate) SetDate(v time.Time) *DailyCompletionUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableDate(v *time.Time) *DailyCompletionUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DailyCompletionUpdate) SetCompletedAt(v time.Time) *DailyCompletionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableCompletedAt(v *time.Time) *DailyCompletionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// SetQualityScore sets the "quality_score" field.
func (_u *DailyCompletionUpdate) SetQualityScore(v int) *DailyCompletionUpdate {
	_u.mutation.ResetQualityScore()
	_u.mutation.SetQualityScore(v)
	return _u
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableQualityScore(v *int) *DailyCompletionUpdate {
	if v != nil {
		_u.SetQualityScore(*v)
	}
	return _u
}

// AddQualityScore adds value to the "quality_score" field.
func (_u *DailyCompletionUpdate) AddQualityScore(v int) *DailyCompletionUpdate {
	_u.mutation.AddQualityScore(v)
	return _u
}

// ClearQualityScore clears the value of the "quality_score" field.
func (_u *DailyCompletionUpdate) ClearQualityScore() *DailyCompletionUpdate {
	_u.mutation.ClearQualityScore()
	return _u
}

// SetNote sets the "note" field.
func (_u *DailyCompletionUpdate) SetNote(v string) *DailyCompletionUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *DailyCompletionUpdate) SetNillableNote(v *string) *DailyCompletionUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *DailyCompletionUpdate) ClearNote() *DailyCompletionUpdate {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the DailyCompletionMutation object of the builder.
func (_u *DailyCompletionUpdate) Mutation() *DailyCompletionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyCompletionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCompletionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyCompletionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCompletionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DailyCompletionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailycompletion.Table, dailycompletion.Columns, sqlgraph.NewFieldSpec(dailycompletion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailycompletion.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.HabitID(); ok {
		_spec.SetField(dailycompletion.FieldHabitID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailycompletion.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dailycompletion.FieldCompletedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualityScore(); ok {
		_spec.SetField(dailycompletion.FieldQualityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityScore(); ok {
		_spec.AddField(dailycompletion.FieldQualityScore, field.TypeInt, value)
	}
	if _u.mutation.QualityScoreCleared() {
		_spec.ClearField(dailycompletion.FieldQualityScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(dailycompletion.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(dailycompletion.FieldNote, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycompletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyCompletionUpdateOne is the builder for updating a single DailyCompletion entity.
type DailyCompletionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyCompletionMutation
}

// SetUserID sets the "user_id" field.
func (_u *DailyCompletionUpdateOne) SetUserID(v uuid.UUID) *DailyCompletionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableUserID(v *uuid.UUID) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetHabitID sets the "habit_id" field.
func (_u *DailyCompletionUpdateOne) SetHabitID(v uuid.UUID) *DailyCompletionUpdateOne {
	_u.mutation.SetHabitID(v)
	return _u
}

// SetNillableHabitID sets the "habit_id" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableHabitID(v *uuid.UUID) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetHabitID(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyCompletionUpdateOne) SetDate(v time.Time) *DailyCompletionUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableDate(v *time.Time) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DailyCompletionUpdateOne) SetCompletedAt(v time.Time) *DailyCompletionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableCompletedAt(v *time.Time) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// SetQualityScore sets the "quality_score" field.
func (_u *DailyCompletionUpdateOne) SetQualityScore(v int) *DailyCompletionUpdateOne {
	_u.mutation.ResetQualityScore()
	_u.mutation.SetQualityScore(v)
	return _u
}

// SetNillableQualityScore sets the "quality_score" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableQualityScore(v *int) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetQualityScore(*v)
	}
	return _u
}

// AddQualityScore adds value to the "quality_score" field.
func (_u *DailyCompletionUpdateOne) AddQualityScore(v int) *DailyCompletionUpdateOne {
	_u.mutation.AddQualityScore(v)
	return _u
}

// ClearQualityScore clears the value of the "quality_score" field.
func (_u *DailyCompletionUpdateOne) ClearQualityScore() *DailyCompletionUpdateOne {
	_u.mutation.ClearQualityScore()
	return _u
}

// SetNote sets the "note" field.
func (_u *DailyCompletionUpdateOne) SetNote(v string) *DailyCompletionUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *DailyCompletionUpdateOne) SetNillableNote(v *string) *DailyCompletionUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *DailyCompletionUpdateOne) ClearNote() *DailyCompletionUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the DailyCompletionMutation object of the builder.
func (_u *DailyCompletionUpdateOne) Mutation() *DailyCompletionMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyCompletionUpdate builder.
func (_u *DailyCompletionUpdateOne) Where(ps ...predicate.DailyCompletion) *DailyCompletionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyCompletionUpdateOne) Select(field string, fields ...string) *DailyCompletionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyCompletion entity.
func (_u *DailyCompletionUpdateOne) Save(ctx context.Context) (*DailyCompletion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCompletionUpdateOne) SaveX(ctx context.Context) *DailyCompletion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyCompletionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCompletionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DailyCompletionUpdateOne) sqlSave(ctx context.Context) (_node *DailyCompletion, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailycompletion.Table, dailycompletion.Columns, sqlgraph.NewFieldSpec(dailycompletion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyCompletion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailycompletion.FieldID)
		for _, f := range fields {
			if !dailycompletion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailycompletion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailycompletion.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.HabitID(); ok {
		_spec.SetField(dailycompletion.FieldHabitID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailycompletion.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dailycompletion.FieldCompletedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualityScore(); ok {
		_spec.SetField(dailycompletion.FieldQualityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityScore(); ok {
		_spec.AddField(dailycompletion.FieldQualityScore, field.TypeInt, value)
	}
	if _u.mutation.QualityScoreCleared() {
		_spec.ClearField(dailycompletion.FieldQualityScore, field.TypeInt)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(dailycompletion.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(dailycompletion.FieldNote, field.TypeString)
	}
	_node = &DailyCompletion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycompletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
