// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/dailylog"
)

// DailyLog is the model entity for the DailyLog schema.
type DailyLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// MoodScore holds the value of the "mood_score" field.
	MoodScore *int `json:"mood_score,omitempty"`
	// ReflectionNote holds the value of the "reflection_note" field.
	ReflectionNote *string `json:"reflection_note,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary      *string `json:"summary,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailylog.FieldMoodScore:
			values[i] = new(sql.NullInt64)
		case dailylog.FieldReflectionNote, dailylog.FieldSummary:
			values[i] = new(sql.NullString)
		case dailylog.FieldDate:
			values[i] = new(sql.NullTime)
		case dailylog.FieldID, dailylog.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyLog fields.
func (_m *DailyLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailylog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dailylog.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case dailylog.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case dailylog.FieldMoodScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mood_score", values[i])
			} else if value.Valid {
				_m.MoodScore = new(int)
				*_m.MoodScore = int(value.Int64)
			}
		case dailylog.FieldReflectionNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reflection_note", values[i])
			} else if value.Valid {
				_m.ReflectionNote = new(string)
				*_m.ReflectionNote = value.String
			}
		case dailylog.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = new(string)
				*_m.Summary = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyLog.
// This includes values selected through modifiers, order, etc.
func (_m *DailyLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DailyLog.
// Note that you need to call DailyLog.Unwrap() before calling this method if this DailyLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyLog) Update() *DailyLogUpdateOne {
	return NewDailyLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyLog) Unwrap() *DailyLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyLog) String() string {
	var builder strings.Builder
	builder.WriteString("DailyLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.MoodScore; v != nil {
		builder.WriteString("mood_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReflectionNote; v != nil {
		builder.WriteString("reflection_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Summary; v != nil {
		builder.WriteString("summary=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// DailyLogs is a parsable slice of DailyLog.
type DailyLogs []*DailyLog
