// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/dailylog"
	"github.com/lagom/lagom-server/ent/predicate"
)

// DailyLogUpdate is the builder for updating DailyLog entities.
type DailyLogUpdate struct {
	config
	hooks     []Hook
	mutation  *DailyLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DailyLogUpdate builder.
func (_u *DailyLogUpdate) Where(ps ...predicate.DailyLog) *DailyLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyLogUpdate) SetUserID(v uuid.UUID) *DailyLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyLogUpdate) SetNillableUserID(v *uuid.UUID) *DailyLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyLogUpdate) SetDate(v time.Time) *DailyLogUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyLogUpdate) SetNillableDate(v *time.Time) *DailyLogUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetMoodScore sets the "mood_score" field.
func (_u *DailyLogUpdate) SetMoodScore(v int) *DailyLogUpdate {
	_u.mutation.ResetMoodScore()
	_u.mutation.SetMoodScore(v)
	return _u
}

// SetNillableMoodScore sets the "mood_score" field if the given value is not nil.
func (_u *DailyLogUpdate) SetNillableMoodScore(v *int) *DailyLogUpdate {
	if v != nil {
		_u.SetMoodScore(*v)
	}
	return _u
}

// AddMoodScore adds value to the "mood_score" field.
func (_u *DailyLogUpdate) AddMoodScore(v int) *DailyLogUpdate {
	_u.mutation.AddMoodScore(v)
	return _u
}

// ClearMoodScore clears the value of the "mood_score" field.
func (_u *DailyLogUpdate) ClearMoodScore() *DailyLogUpdate {
	_u.mutation.ClearMoodScore()
	return _u
}

// SetReflectionNote sets the "reflection_note" field.
func (_u *DailyLogUpdate) SetReflectionNote(v string) *DailyLogUpdate {
	_u.mutation.SetReflectionNote(v)
	return _u
}

// SetNillableReflectionNote sets the "reflection_note" field if the given value is not nil.
func (_u *DailyLogUpdate) SetNillableReflectionNote(v *string) *DailyLogUpdate {
	if v != nil {
		_u.SetReflectionNote(*v)
	}
	return _u
}

// ClearReflectionNote clears the value of the "reflection_note" field.
func (_u *DailyLogUpdate) ClearReflectionNote() *DailyLogUpdate {
	_u.mutation.ClearReflectionNote()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *DailyLogUpdate) SetSummary(v string) *DailyLogUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *DailyLogUpdate) SetNillableSummary(v *string) *DailyLogUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *DailyLogUpdate) ClearSummary() *DailyLogUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// Mutation returns the DailyLogMutation object of the builder.
func (_u *DailyLogUpdate) Mutation() *DailyLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DailyLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DailyLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DailyLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailylog.Table, dailylog.Columns, sqlgraph.NewFieldSpec(dailylog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailylog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailylog.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MoodScore(); ok {
		_spec.SetField(dailylog.FieldMoodScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMoodScore(); ok {
		_spec.AddField(dailylog.FieldMoodScore, field.TypeInt, value)
	}
	if _u.mutation.MoodScoreCleared() {
		_spec.ClearField(dailylog.FieldMoodScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ReflectionNote(); ok {
		_spec.SetField(dailylog.FieldReflectionNote, field.TypeString, value)
	}
	if _u.mutation.ReflectionNoteCleared() {
		_spec.ClearField(dailylog.FieldReflectionNote, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(dailylog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(dailylog.FieldSummary, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyLogUpdateOne is the builder for updating a single DailyLog entity.
type DailyLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DailyLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *DailyLogUpdateOne) SetUserID(v uuid.UUID) *DailyLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyLogUpdateOne) SetNillableUserID(v *uuid.UUID) *DailyLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyLogUpdateOne) SetDate(v time.Time) *DailyLogUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyLogUpdateOne) SetNillableDate(v *time.Time) *DailyLogUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetMoodScore sets the "mood_score" field.
func (_u *DailyLogUpdateOne) SetMoodScore(v int) *DailyLogUpdateOne {
	_u.mutation.ResetMoodScore()
	_u.mutation.SetMoodScore(v)
	return _u
}

// SetNillableMoodScore sets the "mood_score" field if the given value is not nil.
func (_u *DailyLogUpdateOne) SetNillableMoodScore(v *int) *DailyLogUpdateOne {
	if v != nil {
		_u.SetMoodScore(*v)
	}
	return _u
}

// AddMoodScore adds value to the "mood_score" field.
func (_u *DailyLogUpdateOne) AddMoodScore(v int) *DailyLogUpdateOne {
	_u.mutation.AddMoodScore(v)
	return _u
}

// ClearMoodScore clears the value of the "mood_score" field.
func (_u *DailyLogUpdateOne) ClearMoodScore() *DailyLogUpdateOne {
	_u.mutation.ClearMoodScore()
	return _u
}

// SetReflectionNote sets the "reflection_note" field.
func (_u *DailyLogUpdateOne) SetReflectionNote(v string) *DailyLogUpdateOne {
	_u.mutation.SetReflectionNote(v)
	return _u
}

// SetNillableReflectionNote sets the "reflection_note" field if the given value is not nil.
func (_u *DailyLogUpdateOne) SetNillableReflectionNote(v *string) *DailyLogUpdateOne {
	if v != nil {
		_u.SetReflectionNote(*v)
	}
	return _u
}

// ClearReflectionNote clears the value of the "reflection_note" field.
func (_u *DailyLogUpdateOne) ClearReflectionNote() *DailyLogUpdateOne {
	_u.mutation.ClearReflectionNote()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *DailyLogUpdateOne) SetSummary(v string) *DailyLogUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *DailyLogUpdateOne) SetNillableSummary(v *string) *DailyLogUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *DailyLogUpdateOne) ClearSummary() *DailyLogUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// Mutation returns the DailyLogMutation object of the builder.
func (_u *DailyLogUpdateOne) Mutation() *DailyLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyLogUpdate builder.
func (_u *DailyLogUpdateOne) Where(ps ...predicate.DailyLog) *DailyLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyLogUpdateOne) Select(field string, fields ...string) *DailyLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyLog entity.
func (_u *DailyLogUpdateOne) Save(ctx context.Context) (*DailyLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyLogUpdateOne) SaveX(ctx context.Context) *DailyLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DailyLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DailyLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DailyLogUpdateOne) sqlSave(ctx context.Context) (_node *DailyLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(dailylog.Table, dailylog.Columns, sqlgraph.NewFieldSpec(dailylog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailylog.FieldID)
		for _, f := range fields {
			if !dailylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailylog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailylog.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MoodScore(); ok {
		_spec.SetField(dailylog.FieldMoodScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMoodScore(); ok {
		_spec.AddField(dailylog.FieldMoodScore, field.TypeInt, value)
	}
	if _u.mutation.MoodScoreCleared() {
		_spec.ClearField(dailylog.FieldMoodScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ReflectionNote(); ok {
		_spec.SetField(dailylog.FieldReflectionNote, field.TypeString, value)
	}
	if _u.mutation.ReflectionNoteCleared() {
		_spec.ClearField(dailylog.FieldReflectionNote, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(dailylog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(dailylog.FieldSummary, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DailyLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
