// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/focussession"
)

// FocusSessionCreate is the builder for creating a FocusSession entity.
type FocusSessionCreate struct {
	config
	mutation *FocusSessionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *FocusSessionCreate) SetUserID(v uuid.UUID) *FocusSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *FocusSessionCreate) SetStartTime(v time.Time) *FocusSessionCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetDuration sets the "duration" field.
func (_c *FocusSessionCreate) SetDuration(v int) *FocusSessionCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetFocusQualityScore sets the "focus_quality_score" field.
func (_c *FocusSessionCreate) SetFocusQualityScore(v float64) *FocusSessionCreate {
	_c.mutation.SetFocusQualityScore(v)
	return _c
}

// SetNillableFocusQualityScore sets the "focus_quality_score" field if the given value is not nil.
func (_c *FocusSessionCreate) SetNillableFocusQualityScore(v *float64) *FocusSessionCreate {
	if v != nil {
		_c.SetFocusQualityScore(*v)
	}
	return _c
}

// SetDistractions sets the "distractions" field.
func (_c *FocusSessionCreate) SetDistractions(v []string) *FocusSessionCreate {
	_c.mutation.SetDistractions(v)
	return _c
}

// SetContext sets the "context" field.
func (_c *FocusSessionCreate) SetContext(v string) *FocusSessionCreate {
	_c.mutation.SetContext(v)
	return _c
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_c *FocusSessionCreate) SetNillableContext(v *string) *FocusSessionCreate {
	if v != nil {
		_c.SetContext(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FocusSessionCreate) SetCreatedAt(v time.Time) *FocusSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FocusSessionCreate) SetNillableCreatedAt(v *time.Time) *FocusSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FocusSessionCreate) SetID(v uuid.UUID) *FocusSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FocusSessionCreate) SetNillableID(v *uuid.UUID) *FocusSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FocusSessionMutation object of the builder.
func (_c *FocusSessionCreate) Mutation() *FocusSessionMutation {
	return _c.mutation
}

// Save creates the FocusSession in the database.
func (_c *FocusSessionCreate) Save(ctx context.Context) (*FocusSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FocusSessionCreate) SaveX(ctx context.Context) *FocusSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FocusSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FocusSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FocusSessionCreate) defaults() {
	if _, ok := _c.mutation.Distractions(); !ok {
		v := focussession.DefaultDistractions
		_c.mutation.SetDistractions(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := focussession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := focussession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FocusSessionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FocusSession.user_id"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "FocusSession.start_time"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "FocusSession.duration"`)}
	}
	if v, ok := _c.mutation.Duration(); ok {
		if err := focussession.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "FocusSession.duration": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Distractions(); !ok {
		return &ValidationError{Name: "distractions", err: errors.New(`ent: missing required field "FocusSession.distractions"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FocusSession.created_at"`)}
	}
	return nil
}

func (_c *FocusSessionCreate) sqlSave(ctx context.Context) (*FocusSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FocusSessionCreate) createSpec() (*FocusSession, *sqlgraph.CreateSpec) {
	var (
		_node = &FocusSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(focussession.Table, sqlgraph.NewFieldSpec(focussession.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(focussession.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(focussession.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(focussession.FieldDuration, field.TypeInt, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.FocusQualityScore(); ok {
		_spec.SetField(focussession.FieldFocusQualityScore, field.TypeFloat64, value)
		_node.FocusQualityScore = &value
	}
	if value, ok := _c.mutation.Distractions(); ok {
		_spec.SetField(focussession.FieldDistractions, field.TypeJSON, value)
		_node.Distractions = value
	}
	if value, ok := _c.mutation.Context(); ok {
		_spec.SetField(focussession.FieldContext, field.TypeString, value)
		_node.Context = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(focussession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// FocusSessionCreateBulk is the builder for creating many FocusSession entities in bulk.
type FocusSessionCreateBulk struct {
	config
	err      error
	builders []*FocusSessionCreate
}

// Save creates the FocusSession entities in the database.
func (_c *FocusSessionCreateBulk) Save(ctx context.Context) ([]*FocusSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FocusSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FocusSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FocusSessionCreateBulk) SaveX(ctx context.Context) []*FocusSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FocusSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FocusSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
