// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/focussession"
)

// FocusSession is the model entity for the FocusSession schema.
type FocusSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// StartTime holds the value of the "start_time" field.
	StartTime time.Time `json:"start_time,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration int `json:"duration,omitempty"`
	// FocusQualityScore holds the value of the "focus_quality_score" field.
	FocusQualityScore *float64 `json:"focus_quality_score,omitempty"`
	// Distractions holds the value of the "distractions" field.
	Distractions []string `json:"distractions,omitempty"`
	// Context holds the value of the "context" field.
	Context *string `json:"context,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FocusSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case focussession.FieldDistractions:
			values[i] = new([]byte)
		case focussession.FieldFocusQualityScore:
			values[i] = new(sql.NullFloat64)
		case focussession.FieldDuration:
			values[i] = new(sql.NullInt64)
		case focussession.FieldContext:
			values[i] = new(sql.NullString)
		case focussession.FieldStartTime, focussession.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case focussession.FieldID, focussession.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FocusSession fields.
func (_m *FocusSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case focussession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case focussession.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case focussession.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = value.Time
			}
		case focussession.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				_m.Duration = int(value.Int64)
			}
		case focussession.FieldFocusQualityScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field focus_quality_score", values[i])
			} else if value.Valid {
				_m.FocusQualityScore = new(float64)
				*_m.FocusQualityScore = value.Float64
			}
		case focussession.FieldDistractions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field distractions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Distractions); err != nil {
					return fmt.Errorf("unmarshal field distractions: %w", err)
				}
			}
		case focussession.FieldContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value.Valid {
				_m.Context = new(string)
				*_m.Context = value.String
			}
		case focussession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FocusSession.
// This includes values selected through modifiers, order, etc.
func (_m *FocusSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FocusSession.
// Note that you need to call FocusSession.Unwrap() before calling this method if this FocusSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FocusSession) Update() *FocusSessionUpdateOne {
	return NewFocusSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FocusSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FocusSession) Unwrap() *FocusSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FocusSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FocusSession) String() string {
	var builder strings.Builder
	builder.WriteString("FocusSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("start_time=")
	builder.WriteString(_m.StartTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.Duration))
	builder.WriteString(", ")
	if v := _m.FocusQualityScore; v != nil {
		builder.WriteString("focus_quality_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("distractions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Distractions))
	builder.WriteString(", ")
	if v := _m.Context; v != nil {
		builder.WriteString("context=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FocusSessions is a parsable slice of FocusSession.
type FocusSessions []*FocusSession
