// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/habit"
	"github.com/lagom/lagom-server/ent/predicate"
)

// HabitUpdate is the builder for updating Habit entities.
type HabitUpdate struct {
	config
	hooks     []Hook
	mutation  *HabitMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the HabitUpdate builder.
func (_u *HabitUpdate) Where(ps ...predicate.Habit) *HabitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *HabitUpdate) SetUserID(v uuid.UUID) *HabitUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableUserID(v *uuid.UUID) *HabitUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HabitUpdate) SetTitle(v string) *HabitUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableTitle(v *string) *HabitUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *HabitUpdate) SetCategory(v string) *HabitUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableCategory(v *string) *HabitUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HabitUpdate) SetDescription(v string) *HabitUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableDescription(v *string) *HabitUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HabitUpdate) ClearDescription() *HabitUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *HabitUpdate) SetPriority(v int) *HabitUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *HabitUpdate) SetNillablePriority(v *int) *HabitUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *HabitUpdate) AddPriority(v int) *HabitUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetFrequencyType sets the "frequency_type" field.
func (_u *HabitUpdate) SetFrequencyType(v string) *HabitUpdate {
	_u.mutation.SetFrequencyType(v)
	return _u
}

// SetNillableFrequencyType sets the "frequency_type" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableFrequencyType(v *string) *HabitUpdate {
	if v != nil {
		_u.SetFrequencyType(*v)
	}
	return _u
}

// SetTargetDays sets the "target_days" field.
func (_u *HabitUpdate) SetTargetDays(v []int) *HabitUpdate {
	_u.mutation.SetTargetDays(v)
	return _u
}

// AppendTargetDays appends value to the "target_days" field.
func (_u *HabitUpdate) AppendTargetDays(v []int) *HabitUpdate {
	_u.mutation.AppendTargetDays(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *HabitUpdate) SetIsActive(v bool) *HabitUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableIsActive(v *bool) *HabitUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCurrentPhase sets the "current_phase" field.
func (_u *HabitUpdate) SetCurrentPhase(v int) *HabitUpdate {
	_u.mutation.ResetCurrentPhase()
	_u.mutation.SetCurrentPhase(v)
	return _u
}

// SetNillableCurrentPhase sets the "current_phase" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableCurrentPhase(v *int) *HabitUpdate {
	if v != nil {
		_u.SetCurrentPhase(*v)
	}
	return _u
}

// AddCurrentPhase adds value to the "current_phase" field.
func (_u *HabitUpdate) AddCurrentPhase(v int) *HabitUpdate {
	_u.mutation.AddCurrentPhase(v)
	return _u
}

// SetHsi sets the "hsi" field.
func (_u *HabitUpdate) SetHsi(v float64) *HabitUpdate {
	_u.mutation.ResetHsi()
	_u.mutation.SetHsi(v)
	return _u
}

// SetNillableHsi sets the "hsi" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableHsi(v *float64) *HabitUpdate {
	if v != nil {
		_u.SetHsi(*v)
	}
	return _u
}

// AddHsi adds value to the "hsi" field.
func (_u *HabitUpdate) AddHsi(v float64) *HabitUpdate {
	_u.mutation.AddHsi(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *HabitUpdate) SetCreatedAt(v time.Time) *HabitUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *HabitUpdate) SetNillableCreatedAt(v *time.Time) *HabitUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HabitUpdate) SetUpdatedAt(v time.Time) *HabitUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HabitMutation object of the builder.
func (_u *HabitUpdate) Mutation() *HabitMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HabitUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HabitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HabitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HabitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HabitUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := habit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HabitUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := habit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Habit.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := habit.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Habit.category": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HabitUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HabitUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HabitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(habit.Table, habit.Columns, sqlgraph.NewFieldSpec(habit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(habit.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(habit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(habit.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(habit.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(habit.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(habit.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(habit.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FrequencyType(); ok {
		_spec.SetField(habit.FieldFrequencyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDays(); ok {
		_spec.SetField(habit.FieldTargetDays, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetDays(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, habit.FieldTargetDays, value)
		})
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(habit.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentPhase(); ok {
		_spec.SetField(habit.FieldCurrentPhase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPhase(); ok {
		_spec.AddField(habit.FieldCurrentPhase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Hsi(); ok {
		_spec.SetField(habit.FieldHsi, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHsi(); ok {
		_spec.AddField(habit.FieldHsi, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(habit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(habit.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{habit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HabitUpdateOne is the builder for updating a single Habit entity.
type HabitUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *HabitMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *HabitUpdateOne) SetUserID(v uuid.UUID) *HabitUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableUserID(v *uuid.UUID) *HabitUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HabitUpdateOne) SetTitle(v string) *HabitUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableTitle(v *string) *HabitUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *HabitUpdateOne) SetCategory(v string) *HabitUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableCategory(v *string) *HabitUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *HabitUpdateOne) SetDescription(v string) *HabitUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableDescription(v *string) *HabitUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *HabitUpdateOne) ClearDescription() *HabitUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *HabitUpdateOne) SetPriority(v int) *HabitUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillablePriority(v *int) *HabitUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *HabitUpdateOne) AddPriority(v int) *HabitUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetFrequencyType sets the "frequency_type" field.
func (_u *HabitUpdateOne) SetFrequencyType(v string) *HabitUpdateOne {
	_u.mutation.SetFrequencyType(v)
	return _u
}

// SetNillableFrequencyType sets the "frequency_type" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableFrequencyType(v *string) *HabitUpdateOne {
	if v != nil {
		_u.SetFrequencyType(*v)
	}
	return _u
}

// SetTargetDays sets the "target_days" field.
func (_u *HabitUpdateOne) SetTargetDays(v []int) *HabitUpdateOne {
	_u.mutation.SetTargetDays(v)
	return _u
}

// AppendTargetDays appends value to the "target_days" field.
func (_u *HabitUpdateOne) AppendTargetDays(v []int) *HabitUpdateOne {
	_u.mutation.AppendTargetDays(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *HabitUpdateOne) SetIsActive(v bool) *HabitUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableIsActive(v *bool) *HabitUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCurrentPhase sets the "current_phase" field.
func (_u *HabitUpdateOne) SetCurrentPhase(v int) *HabitUpdateOne {
	_u.mutation.ResetCurrentPhase()
	_u.mutation.SetCurrentPhase(v)
	return _u
}

// SetNillableCurrentPhase sets the "current_phase" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableCurrentPhase(v *int) *HabitUpdateOne {
	if v != nil {
		_u.SetCurrentPhase(*v)
	}
	return _u
}

// AddCurrentPhase adds value to the "current_phase" field.
func (_u *HabitUpdateOne) AddCurrentPhase(v int) *HabitUpdateOne {
	_u.mutation.AddCurrentPhase(v)
	return _u
}

// SetHsi sets the "hsi" field.
func (_u *HabitUpdateOne) SetHsi(v float64) *HabitUpdateOne {
	_u.mutation.ResetHsi()
	_u.mutation.SetHsi(v)
	return _u
}

// SetNillableHsi sets the "hsi" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableHsi(v *float64) *HabitUpdateOne {
	if v != nil {
		_u.SetHsi(*v)
	}
	return _u
}

// AddHsi adds value to the "hsi" field.
func (_u *HabitUpdateOne) AddHsi(v float64) *HabitUpdateOne {
	_u.mutation.AddHsi(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *HabitUpdateOne) SetCreatedAt(v time.Time) *HabitUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *HabitUpdateOne) SetNillableCreatedAt(v *time.Time) *HabitUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HabitUpdateOne) SetUpdatedAt(v time.Time) *HabitUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HabitMutation object of the builder.
func (_u *HabitUpdateOne) Mutation() *HabitMutation {
	return _u.mutation
}

// Where appends a list predicates to the HabitUpdate builder.
func (_u *HabitUpdateOne) Where(ps ...predicate.Habit) *HabitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HabitUpdateOne) Select(field string, fields ...string) *HabitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Habit entity.
func (_u *HabitUpdateOne) Save(ctx context.Context) (*Habit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HabitUpdateOne) SaveX(ctx context.Context) *Habit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HabitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HabitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HabitUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := habit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HabitUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := habit.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Habit.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := habit.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Habit.category": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HabitUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HabitUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HabitUpdateOne) sqlSave(ctx context.Context) (_node *Habit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(habit.Table, habit.Columns, sqlgraph.NewFieldSpec(habit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Habit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, habit.FieldID)
		for _, f := range fields {
			if !habit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != habit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(habit.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(habit.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(habit.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(habit.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(habit.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(habit.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(habit.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FrequencyType(); ok {
		_spec.SetField(habit.FieldFrequencyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDays(); ok {
		_spec.SetField(habit.FieldTargetDays, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTargetDays(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, habit.FieldTargetDays, value)
		})
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(habit.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentPhase(); ok {
		_spec.SetField(habit.FieldCurrentPhase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPhase(); ok {
		_spec.AddField(habit.FieldCurrentPhase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Hsi(); ok {
		_spec.SetField(habit.FieldHsi, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHsi(); ok {
		_spec.AddField(habit.FieldHsi, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(habit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(habit.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Habit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{habit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
