// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/microaction"
)

// MicroActionCreate is the builder for creating a MicroAction entity.
type MicroActionCreate struct {
	config
	mutation *MicroActionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHabitID sets the "habit_id" field.
func (_c *MicroActionCreate) SetHabitID(v uuid.UUID) *MicroActionCreate {
	_c.mutation.SetHabitID(v)
	return _c
}

// SetPhase sets the "phase" field.
func (_c *MicroActionCreate) SetPhase(v int) *MicroActionCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetDayInPhase sets the "day_in_phase" field.
func (_c *MicroActionCreate) SetDayInPhase(v int) *MicroActionCreate {
	_c.mutation.SetDayInPhase(v)
	return _c
}

// SetActionText sets the "action_text" field.
func (_c *MicroActionCreate) SetActionText(v string) *MicroActionCreate {
	_c.mutation.SetActionText(v)
	return _c
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (_c *MicroActionCreate) SetEstimatedDuration(v int) *MicroActionCreate {
	_c.mutation.SetEstimatedDuration(v)
	return _c
}

// SetNillableEstimatedDuration sets the "estimated_duration" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableEstimatedDuration(v *int) *MicroActionCreate {
	if v != nil {
		_c.SetEstimatedDuration(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *MicroActionCreate) SetIsDefault(v bool) *MicroActionCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableIsDefault(v *bool) *MicroActionCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MicroActionCreate) SetCreatedAt(v time.Time) *MicroActionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableCreatedAt(v *time.Time) *MicroActionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MicroActionCreate) SetID(v uuid.UUID) *MicroActionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableID(v *uuid.UUID) *MicroActionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MicroActionMutation object of the builder.
func (_c *MicroActionCreate) Mutation() *MicroActionMutation {
	return _c.mutation
}

// Save creates the MicroAction in the database.
func (_c *MicroActionCreate) Save(ctx context.Context) (*MicroAction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MicroActionCreate) SaveX(ctx context.Context) *MicroAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicroActionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicroActionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MicroActionCreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := microaction.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := microaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := microaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MicroActionCreate) check() error {
	if _, ok := _c.mutation.HabitID(); !ok {
		return &ValidationError{Name: "habit_id", err: errors.New(`ent: missing required field "MicroAction.habit_id"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "MicroAction.phase"`)}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := microaction.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "MicroAction.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DayInPhase(); !ok {
		return &ValidationError{Name: "day_in_phase", err: errors.New(`ent: missing required field "MicroAction.day_in_phase"`)}
	}
	if v, ok := _c.mutation.DayInPhase(); ok {
		if err := microaction.DayInPhaseValidator(v); err != nil {
			return &ValidationError{Name: "day_in_phase", err: fmt.Errorf(`ent: validator failed for field "MicroAction.day_in_phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionText(); !ok {
		return &ValidationError{Name: "action_text", err: errors.New(`ent: missing required field "MicroAction.action_text"`)}
	}
	if v, ok := _c.mutation.ActionText(); ok {
		if err := microaction.ActionTextValidator(v); err != nil {
			return &ValidationError{Name: "action_text", err: fmt.Errorf(`ent: validator failed for field "MicroAction.action_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "MicroAction.is_default"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MicroAction.created_at"`)}
	}
	return nil
}

func (_c *MicroActionCreate) sqlSave(ctx context.Context) (*MicroAction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MicroActionCreate) createSpec() (*MicroAction, *sqlgraph.CreateSpec) {
	var (
		_node = &MicroAction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(microaction.Table, sqlgraph.NewFieldSpec(microaction.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.HabitID(); ok {
		_spec.SetField(microaction.FieldHabitID, field.TypeUUID, value)
		_node.HabitID = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(microaction.FieldPhase, field.TypeInt, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.DayInPhase(); ok {
		_spec.SetField(microaction.FieldDayInPhase, field.TypeInt, value)
		_node.DayInPhase = value
	}
	if value, ok := _c.mutation.ActionText(); ok {
		_spec.SetField(microaction.FieldActionText, field.TypeString, value)
		_node.ActionText = value
	}
	if value, ok := _c.mutation.EstimatedDuration(); ok {
		_spec.SetField(microaction.FieldEstimatedDuration, field.TypeInt, value)
		_node.EstimatedDuration = &value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(microaction.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(microaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MicroAction.Create().
//		SetHabitID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MicroActionUpsert) {
//			SetHabitID(v+v).
//		}).
//		Exec(ctx)
func (_c *MicroActionCreate) OnConflict(opts ...sql.ConflictOption) *MicroActionUpsertOne {
	_c.conflict = opts
	return &MicroActionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MicroActionCreate) OnConflictColumns(columns ...string) *MicroActionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MicroActionUpsertOne{
		create: _c,
	}
}

type (
	// MicroActionUpsertOne is the builder for "upsert"-ing
	//  one MicroAction node.
	MicroActionUpsertOne struct {
		create *MicroActionCreate
	}

	// MicroActionUpsert is the "OnConflict" setter.
	MicroActionUpsert struct {
		*sql.UpdateSet
	}
)

// SetHabitID sets the "habit_id" field.
func (u *MicroActionUpsert) SetHabitID(v uuid.UUID) *MicroActionUpsert {
	u.Set(microaction.FieldHabitID, v)
	return u
}

// UpdateHabitID sets the "habit_id" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateHabitID() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldHabitID)
	return u
}

// SetPhase sets the "phase" field.
func (u *MicroActionUpsert) SetPhase(v int) *MicroActionUpsert {
	u.Set(microaction.FieldPhase, v)
	return u
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdatePhase() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldPhase)
	return u
}

// AddPhase adds v to the "phase" field.
func (u *MicroActionUpsert) AddPhase(v int) *MicroActionUpsert {
	u.Add(microaction.FieldPhase, v)
	return u
}

// SetDayInPhase sets the "day_in_phase" field.
func (u *MicroActionUpsert) SetDayInPhase(v int) *MicroActionUpsert {
	u.Set(microaction.FieldDayInPhase, v)
	return u
}

// UpdateDayInPhase sets the "day_in_phase" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateDayInPhase() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldDayInPhase)
	return u
}

// AddDayInPhase adds v to the "day_in_phase" field.
func (u *MicroActionUpsert) AddDayInPhase(v int) *MicroActionUpsert {
	u.Add(microaction.FieldDayInPhase, v)
	return u
}

// SetActionText sets the "action_text" field.
func (u *MicroActionUpsert) SetActionText(v string) *MicroActionUpsert {
	u.Set(microaction.FieldActionText, v)
	return u
}

// UpdateActionText sets the "action_text" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateActionText() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldActionText)
	return u
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (u *MicroActionUpsert) SetEstimatedDuration(v int) *MicroActionUpsert {
	u.Set(microaction.FieldEstimatedDuration, v)
	return u
}

// UpdateEstimatedDuration sets the "estimated_duration" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateEstimatedDuration() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldEstimatedDuration)
	return u
}

// AddEstimatedDuration adds v to the "estimated_duration" field.
func (u *MicroActionUpsert) AddEstimatedDuration(v int) *MicroActionUpsert {
	u.Add(microaction.FieldEstimatedDuration, v)
	return u
}

// ClearEstimatedDuration clears the value of the "estimated_duration" field.
func (u *MicroActionUpsert) ClearEstimatedDuration() *MicroActionUpsert {
	u.SetNull(microaction.FieldEstimatedDuration)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *MicroActionUpsert) SetIsDefault(v bool) *MicroActionUpsert {
	u.Set(microaction.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateIsDefault() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldIsDefault)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MicroActionUpsert) SetCreatedAt(v time.Time) *MicroActionUpsert {
	u.Set(microaction.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MicroActionUpsert) UpdateCreatedAt() *MicroActionUpsert {
	u.SetExcluded(microaction.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(microaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MicroActionUpsertOne) UpdateNewValues() *MicroActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(microaction.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MicroActionUpsertOne) Ignore() *MicroActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MicroActionUpsertOne) DoNothing() *MicroActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MicroActionCreate.OnConflict
// documentation for more info.
func (u *MicroActionUpsertOne) Update(set func(*MicroActionUpsert)) *MicroActionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MicroActionUpsert{UpdateSet: update})
	}))
	return u
}

// SetHabitID sets the "habit_id" field.
func (u *MicroActionUpsertOne) SetHabitID(v uuid.UUID) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetHabitID(v)
	})
}

// UpdateHabitID sets the "habit_id" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateHabitID() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateHabitID()
	})
}

// SetPhase sets the "phase" field.
func (u *MicroActionUpsertOne) SetPhase(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetPhase(v)
	})
}

// AddPhase adds v to the "phase" field.
func (u *MicroActionUpsertOne) AddPhase(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdatePhase() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdatePhase()
	})
}

// SetDayInPhase sets the "day_in_phase" field.
func (u *MicroActionUpsertOne) SetDayInPhase(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetDayInPhase(v)
	})
}

// AddDayInPhase adds v to the "day_in_phase" field.
func (u *MicroActionUpsertOne) AddDayInPhase(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddDayInPhase(v)
	})
}

// UpdateDayInPhase sets the "day_in_phase" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateDayInPhase() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateDayInPhase()
	})
}

// SetActionText sets the "action_text" field.
func (u *MicroActionUpsertOne) SetActionText(v string) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetActionText(v)
	})
}

// UpdateActionText sets the "action_text" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateActionText() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateActionText()
	})
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (u *MicroActionUpsertOne) SetEstimatedDuration(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetEstimatedDuration(v)
	})
}

// AddEstimatedDuration adds v to the "estimated_duration" field.
func (u *MicroActionUpsertOne) AddEstimatedDuration(v int) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddEstimatedDuration(v)
	})
}

// UpdateEstimatedDuration sets the "estimated_duration" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateEstimatedDuration() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateEstimatedDuration()
	})
}

// ClearEstimatedDuration clears the value of the "estimated_duration" field.
func (u *MicroActionUpsertOne) ClearEstimatedDuration() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.ClearEstimatedDuration()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *MicroActionUpsertOne) SetIsDefault(v bool) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateIsDefault() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateIsDefault()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MicroActionUpsertOne) SetCreatedAt(v time.Time) *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MicroActionUpsertOne) UpdateCreatedAt() *MicroActionUpsertOne {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *MicroActionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MicroActionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MicroActionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MicroActionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MicroActionUpsertOne.ID is not supported by MySQL driver. Use MicroActionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MicroActionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MicroActionCreateBulk is the builder for creating many MicroAction entities in bulk.
type MicroActionCreateBulk struct {
	config
	err      error
	builders []*MicroActionCreate
	conflict []sql.ConflictOption
}

// Save creates the MicroAction entities in the database.
func (_c *MicroActionCreateBulk) Save(ctx context.Context) ([]*MicroAction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MicroAction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MicroActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MicroActionCreateBulk) SaveX(ctx context.Context) []*MicroAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicroActionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicroActionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MicroAction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MicroActionUpsert) {
//			SetHabitID(v+v).
//		}).
//		Exec(ctx)
func (_c *MicroActionCreateBulk) OnConflict(opts ...sql.ConflictOption) *MicroActionUpsertBulk {
	_c.conflict = opts
	return &MicroActionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MicroActionCreateBulk) OnConflictColumns(columns ...string) *MicroActionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MicroActionUpsertBulk{
		create: _c,
	}
}

// MicroActionUpsertBulk is the builder for "upsert"-ing
// a bulk of MicroAction nodes.
type MicroActionUpsertBulk struct {
	create *MicroActionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(microaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MicroActionUpsertBulk) UpdateNewValues() *MicroActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(microaction.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MicroAction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MicroActionUpsertBulk) Ignore() *MicroActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MicroActionUpsertBulk) DoNothing() *MicroActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MicroActionCreateBulk.OnConflict
// documentation for more info.
func (u *MicroActionUpsertBulk) Update(set func(*MicroActionUpsert)) *MicroActionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MicroActionUpsert{UpdateSet: update})
	}))
	return u
}

// SetHabitID sets the "habit_id" field.
func (u *MicroActionUpsertBulk) SetHabitID(v uuid.UUID) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetHabitID(v)
	})
}

// UpdateHabitID sets the "habit_id" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateHabitID() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateHabitID()
	})
}

// SetPhase sets the "phase" field.
func (u *MicroActionUpsertBulk) SetPhase(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetPhase(v)
	})
}

// AddPhase adds v to the "phase" field.
func (u *MicroActionUpsertBulk) AddPhase(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddPhase(v)
	})
}

// UpdatePhase sets the "phase" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdatePhase() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdatePhase()
	})
}

// SetDayInPhase sets the "day_in_phase" field.
func (u *MicroActionUpsertBulk) SetDayInPhase(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetDayInPhase(v)
	})
}

// AddDayInPhase adds v to the "day_in_phase" field.
func (u *MicroActionUpsertBulk) AddDayInPhase(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddDayInPhase(v)
	})
}

// UpdateDayInPhase sets the "day_in_phase" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateDayInPhase() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateDayInPhase()
	})
}

// SetActionText sets the "action_text" field.
func (u *MicroActionUpsertBulk) SetActionText(v string) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetActionText(v)
	})
}

// UpdateActionText sets the "action_text" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateActionText() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateActionText()
	})
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (u *MicroActionUpsertBulk) SetEstimatedDuration(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetEstimatedDuration(v)
	})
}

// AddEstimatedDuration adds v to the "estimated_duration" field.
func (u *MicroActionUpsertBulk) AddEstimatedDuration(v int) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.AddEstimatedDuration(v)
	})
}

// UpdateEstimatedDuration sets the "estimated_duration" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateEstimatedDuration() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateEstimatedDuration()
	})
}

// ClearEstimatedDuration clears the value of the "estimated_duration" field.
func (u *MicroActionUpsertBulk) ClearEstimatedDuration() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.ClearEstimatedDuration()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *MicroActionUpsertBulk) SetIsDefault(v bool) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateIsDefault() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateIsDefault()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MicroActionUpsertBulk) SetCreatedAt(v time.Time) *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MicroActionUpsertBulk) UpdateCreatedAt() *MicroActionUpsertBulk {
	return u.Update(func(s *MicroActionUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *MicroActionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MicroActionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MicroActionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MicroActionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
