// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/microaction"
)

// MicroActionCreate is the builder for creating a MicroAction entity.
type MicroActionCreate struct {
	config
	mutation *MicroActionMutation
	hooks    []Hook
}

// SetHabitID sets the "habit_id" field.
func (_c *MicroActionCreate) SetHabitID(v uuid.UUID) *MicroActionCreate {
	_c.mutation.SetHabitID(v)
	return _c
}

// SetPhase sets the "phase" field.
func (_c *MicroActionCreate) SetPhase(v int) *MicroActionCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetDayInPhase sets the "day_in_phase" field.
func (_c *MicroActionCreate) SetDayInPhase(v int) *MicroActionCreate {
	_c.mutation.SetDayInPhase(v)
	return _c
}

// SetActionText sets the "action_text" field.
func (_c *MicroActionCreate) SetActionText(v string) *MicroActionCreate {
	_c.mutation.SetActionText(v)
	return _c
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (_c *MicroActionCreate) SetEstimatedDuration(v int) *MicroActionCreate {
	_c.mutation.SetEstimatedDuration(v)
	return _c
}

// SetNillableEstimatedDuration sets the "estimated_duration" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableEstimatedDuration(v *int) *MicroActionCreate {
	if v != nil {
		_c.SetEstimatedDuration(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *MicroActionCreate) SetIsDefault(v bool) *MicroActionCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableIsDefault(v *bool) *MicroActionCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MicroActionCreate) SetCreatedAt(v time.Time) *MicroActionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableCreatedAt(v *time.Time) *MicroActionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MicroActionCreate) SetID(v uuid.UUID) *MicroActionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MicroActionCreate) SetNillableID(v *uuid.UUID) *MicroActionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MicroActionMutation object of the builder.
func (_c *MicroActionCreate) Mutation() *MicroActionMutation {
	return _c.mutation
}

// Save creates the MicroAction in the database.
func (_c *MicroActionCreate) Save(ctx context.Context) (*MicroAction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MicroActionCreate) SaveX(ctx context.Context) *MicroAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicroActionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicroActionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MicroActionCreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := microaction.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := microaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := microaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MicroActionCreate) check() error {
	if _, ok := _c.mutation.HabitID(); !ok {
		return &ValidationError{Name: "habit_id", err: errors.New(`ent: missing required field "MicroAction.habit_id"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "MicroAction.phase"`)}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := microaction.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "MicroAction.phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DayInPhase(); !ok {
		return &ValidationError{Name: "day_in_phase", err: errors.New(`ent: missing required field "MicroAction.day_in_phase"`)}
	}
	if v, ok := _c.mutation.DayInPhase(); ok {
		if err := microaction.DayInPhaseValidator(v); err != nil {
			return &ValidationError{Name: "day_in_phase", err: fmt.Errorf(`ent: validator failed for field "MicroAction.day_in_phase": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionText(); !ok {
		return &ValidationError{Name: "action_text", err: errors.New(`ent: missing required field "MicroAction.action_text"`)}
	}
	if v, ok := _c.mutation.ActionText(); ok {
		if err := microaction.ActionTextValidator(v); err != nil {
			return &ValidationError{Name: "action_text", err: fmt.Errorf(`ent: validator failed for field "MicroAction.action_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "MicroAction.is_default"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MicroAction.created_at"`)}
	}
	return nil
}

func (_c *MicroActionCreate) sqlSave(ctx context.Context) (*MicroAction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MicroActionCreate) createSpec() (*MicroAction, *sqlgraph.CreateSpec) {
	var (
		_node = &MicroAction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(microaction.Table, sqlgraph.NewFieldSpec(microaction.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.HabitID(); ok {
		_spec.SetField(microaction.FieldHabitID, field.TypeUUID, value)
		_node.HabitID = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(microaction.FieldPhase, field.TypeInt, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.DayInPhase(); ok {
		_spec.SetField(microaction.FieldDayInPhase, field.TypeInt, value)
		_node.DayInPhase = value
	}
	if value, ok := _c.mutation.ActionText(); ok {
		_spec.SetField(microaction.FieldActionText, field.TypeString, value)
		_node.ActionText = value
	}
	if value, ok := _c.mutation.EstimatedDuration(); ok {
		_spec.SetField(microaction.FieldEstimatedDuration, field.TypeInt, value)
		_node.EstimatedDuration = &value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(microaction.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(microaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MicroActionCreateBulk is the builder for creating many MicroAction entities in bulk.
type MicroActionCreateBulk struct {
	config
	err      error
	builders []*MicroActionCreate
}

// Save creates the MicroAction entities in the database.
func (_c *MicroActionCreateBulk) Save(ctx context.Context) ([]*MicroAction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MicroAction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MicroActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MicroActionCreateBulk) SaveX(ctx context.Context) []*MicroAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicroActionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicroActionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
