// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/usercharacterconfig"
)

// UserCharacterConfigCreate is the builder for creating a UserCharacterConfig entity.
type UserCharacterConfigCreate struct {
	config
	mutation *UserCharacterConfigMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserCharacterConfigCreate) SetUserID(v uuid.UUID) *UserCharacterConfigCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *UserCharacterConfigCreate) SetCharacterID(v string) *UserCharacterConfigCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetCustomName sets the "custom_name" field.
func (_c *UserCharacterConfigCreate) SetCustomName(v string) *UserCharacterConfigCreate {
	_c.mutation.SetCustomName(v)
	return _c
}

// SetNillableCustomName sets the "custom_name" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableCustomName(v *string) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetCustomName(*v)
	}
	return _c
}

// SetCustomAvatarURL sets the "custom_avatar_url" field.
func (_c *UserCharacterConfigCreate) SetCustomAvatarURL(v string) *UserCharacterConfigCreate {
	_c.mutation.SetCustomAvatarURL(v)
	return _c
}

// SetNillableCustomAvatarURL sets the "custom_avatar_url" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableCustomAvatarURL(v *string) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetCustomAvatarURL(*v)
	}
	return _c
}

// SetIntimacyLevel sets the "intimacy_level" field.
func (_c *UserCharacterConfigCreate) SetIntimacyLevel(v int) *UserCharacterConfigCreate {
	_c.mutation.SetIntimacyLevel(v)
	return _c
}

// SetNillableIntimacyLevel sets the "intimacy_level" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableIntimacyLevel(v *int) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetIntimacyLevel(*v)
	}
	return _c
}

// SetIntimacyScore sets the "intimacy_score" field.
func (_c *UserCharacterConfigCreate) SetIntimacyScore(v int) *UserCharacterConfigCreate {
	_c.mutation.SetIntimacyScore(v)
	return _c
}

// SetNillableIntimacyScore sets the "intimacy_score" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableIntimacyScore(v *int) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetIntimacyScore(*v)
	}
	return _c
}

// SetUnlockedStories sets the "unlocked_stories" field.
func (_c *UserCharacterConfigCreate) SetUnlockedStories(v []string) *UserCharacterConfigCreate {
	_c.mutation.SetUnlockedStories(v)
	return _c
}

// SetUnlockedExpressions sets the "unlocked_expressions" field.
func (_c *UserCharacterConfigCreate) SetUnlockedExpressions(v []string) *UserCharacterConfigCreate {
	_c.mutation.SetUnlockedExpressions(v)
	return _c
}

// SetUnlockedDeepNightMode sets the "unlocked_deep_night_mode" field.
func (_c *UserCharacterConfigCreate) SetUnlockedDeepNightMode(v bool) *UserCharacterConfigCreate {
	_c.mutation.SetUnlockedDeepNightMode(v)
	return _c
}

// SetNillableUnlockedDeepNightMode sets the "unlocked_deep_night_mode" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableUnlockedDeepNightMode(v *bool) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetUnlockedDeepNightMode(*v)
	}
	return _c
}

// SetTotalMessages sets the "total_messages" field.
func (_c *UserCharacterConfigCreate) SetTotalMessages(v int) *UserCharacterConfigCreate {
	_c.mutation.SetTotalMessages(v)
	return _c
}

// SetNillableTotalMessages sets the "total_messages" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableTotalMessages(v *int) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetTotalMessages(*v)
	}
	return _c
}

// SetTotalGoalsCompleted sets the "total_goals_completed" field.
func (_c *UserCharacterConfigCreate) SetTotalGoalsCompleted(v int) *UserCharacterConfigCreate {
	_c.mutation.SetTotalGoalsCompleted(v)
	return _c
}

// SetNillableTotalGoalsCompleted sets the "total_goals_completed" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableTotalGoalsCompleted(v *int) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetTotalGoalsCompleted(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *UserCharacterConfigCreate) SetIsActive(v bool) *UserCharacterConfigCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableIsActive(v *bool) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetIsFavorite sets the "is_favorite" field.
func (_c *UserCharacterConfigCreate) SetIsFavorite(v bool) *UserCharacterConfigCreate {
	_c.mutation.SetIsFavorite(v)
	return _c
}

// SetNillableIsFavorite sets the "is_favorite" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableIsFavorite(v *bool) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetIsFavorite(*v)
	}
	return _c
}

// SetSwitchCountThisMonth sets the "switch_count_this_month" field.
func (_c *UserCharacterConfigCreate) SetSwitchCountThisMonth(v int) *UserCharacterConfigCreate {
	_c.mutation.SetSwitchCountThisMonth(v)
	return _c
}

// SetNillableSwitchCountThisMonth sets the "switch_count_this_month" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableSwitchCountThisMonth(v *int) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetSwitchCountThisMonth(*v)
	}
	return _c
}

// SetLastSwitchDate sets the "last_switch_date" field.
func (_c *UserCharacterConfigCreate) SetLastSwitchDate(v time.Time) *UserCharacterConfigCreate {
	_c.mutation.SetLastSwitchDate(v)
	return _c
}

// SetNillableLastSwitchDate sets the "last_switch_date" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableLastSwitchDate(v *time.Time) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetLastSwitchDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCharacterConfigCreate) SetCreatedAt(v time.Time) *UserCharacterConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableCreatedAt(v *time.Time) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCharacterConfigCreate) SetUpdatedAt(v time.Time) *UserCharacterConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableUpdatedAt(v *time.Time) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCharacterConfigCreate) SetID(v uuid.UUID) *UserCharacterConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserCharacterConfigCreate) SetNillableID(v *uuid.UUID) *UserCharacterConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the UserCharacterConfigMutation object of the builder.
func (_c *UserCharacterConfigCreate) Mutation() *UserCharacterConfigMutation {
	return _c.mutation
}

// Save creates the UserCharacterConfig in the database.
func (_c *UserCharacterConfigCreate) Save(ctx context.Context) (*UserCharacterConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCharacterConfigCreate) SaveX(ctx context.Context) *UserCharacterConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCharacterConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCharacterConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCharacterConfigCreate) defaults() {
	if _, ok := _c.mutation.IntimacyLevel(); !ok {
		v := usercharacterconfig.DefaultIntimacyLevel
		_c.mutation.SetIntimacyLevel(v)
	}
	if _, ok := _c.mutation.IntimacyScore(); !ok {
		v := usercharacterconfig.DefaultIntimacyScore
		_c.mutation.SetIntimacyScore(v)
	}
	if _, ok := _c.mutation.UnlockedStories(); !ok {
		v := usercharacterconfig.DefaultUnlockedStories
		_c.mutation.SetUnlockedStories(v)
	}
	if _, ok := _c.mutation.UnlockedExpressions(); !ok {
		v := usercharacterconfig.DefaultUnlockedExpressions
		_c.mutation.SetUnlockedExpressions(v)
	}
	if _, ok := _c.mutation.UnlockedDeepNightMode(); !ok {
		v := usercharacterconfig.DefaultUnlockedDeepNightMode
		_c.mutation.SetUnlockedDeepNightMode(v)
	}
	if _, ok := _c.mutation.TotalMessages(); !ok {
		v := usercharacterconfig.DefaultTotalMessages
		_c.mutation.SetTotalMessages(v)
	}
	if _, ok := _c.mutation.TotalGoalsCompleted(); !ok {
		v := usercharacterconfig.DefaultTotalGoalsCompleted
		_c.mutation.SetTotalGoalsCompleted(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := usercharacterconfig.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.IsFavorite(); !ok {
		v := usercharacterconfig.DefaultIsFavorite
		_c.mutation.SetIsFavorite(v)
	}
	if _, ok := _c.mutation.SwitchCountThisMonth(); !ok {
		v := usercharacterconfig.DefaultSwitchCountThisMonth
		_c.mutation.SetSwitchCountThisMonth(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usercharacterconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usercharacterconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := usercharacterconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCharacterConfigCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserCharacterConfig.user_id"`)}
	}
	if _, ok := _c.mutation.CharacterID(); !ok {
		return &ValidationError{Name: "character_id", err: errors.New(`ent: missing required field "UserCharacterConfig.character_id"`)}
	}
	if v, ok := _c.mutation.CharacterID(); ok {
		if err := usercharacterconfig.CharacterIDValidator(v); err != nil {
			return &ValidationError{Name: "character_id", err: fmt.Errorf(`ent: validator failed for field "UserCharacterConfig.character_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntimacyLevel(); !ok {
		return &ValidationError{Name: "intimacy_level", err: errors.New(`ent: missing required field "UserCharacterConfig.intimacy_level"`)}
	}
	if _, ok := _c.mutation.IntimacyScore(); !ok {
		return &ValidationError{Name: "intimacy_score", err: errors.New(`ent: missing required field "UserCharacterConfig.intimacy_score"`)}
	}
	if _, ok := _c.mutation.UnlockedStories(); !ok {
		return &ValidationError{Name: "unlocked_stories", err: errors.New(`ent: missing required field "UserCharacterConfig.unlocked_stories"`)}
	}
	if _, ok := _c.mutation.UnlockedExpressions(); !ok {
		return &ValidationError{Name: "unlocked_expressions", err: errors.New(`ent: missing required field "UserCharacterConfig.unlocked_expressions"`)}
	}
	if _, ok := _c.mutation.UnlockedDeepNightMode(); !ok {
		return &ValidationError{Name: "unlocked_deep_night_mode", err: errors.New(`ent: missing required field "UserCharacterConfig.unlocked_deep_night_mode"`)}
	}
	if _, ok := _c.mutation.TotalMessages(); !ok {
		return &ValidationError{Name: "total_messages", err: errors.New(`ent: missing required field "UserCharacterConfig.total_messages"`)}
	}
	if _, ok := _c.mutation.TotalGoalsCompleted(); !ok {
		return &ValidationError{Name: "total_goals_completed", err: errors.New(`ent: missing required field "UserCharacterConfig.total_goals_completed"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "UserCharacterConfig.is_active"`)}
	}
	if _, ok := _c.mutation.IsFavorite(); !ok {
		return &ValidationError{Name: "is_favorite", err: errors.New(`ent: missing required field "UserCharacterConfig.is_favorite"`)}
	}
	if _, ok := _c.mutation.SwitchCountThisMonth(); !ok {
		return &ValidationError{Name: "switch_count_this_month", err: errors.New(`ent: missing required field "UserCharacterConfig.switch_count_this_month"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserCharacterConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserCharacterConfig.updated_at"`)}
	}
	return nil
}

func (_c *UserCharacterConfigCreate) sqlSave(ctx context.Context) (*UserCharacterConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCharacterConfigCreate) createSpec() (*UserCharacterConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &UserCharacterConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usercharacterconfig.Table, sqlgraph.NewFieldSpec(usercharacterconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usercharacterconfig.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(usercharacterconfig.FieldCharacterID, field.TypeString, value)
		_node.CharacterID = value
	}
	if value, ok := _c.mutation.CustomName(); ok {
		_spec.SetField(usercharacterconfig.FieldCustomName, field.TypeString, value)
		_node.CustomName = &value
	}
	if value, ok := _c.mutation.CustomAvatarURL(); ok {
		_spec.SetField(usercharacterconfig.FieldCustomAvatarURL, field.TypeString, value)
		_node.CustomAvatarURL = &value
	}
	if value, ok := _c.mutation.IntimacyLevel(); ok {
		_spec.SetField(usercharacterconfig.FieldIntimacyLevel, field.TypeInt, value)
		_node.IntimacyLevel = value
	}
	if value, ok := _c.mutation.IntimacyScore(); ok {
		_spec.SetField(usercharacterconfig.FieldIntimacyScore, field.TypeInt, value)
		_node.IntimacyScore = value
	}
	if value, ok := _c.mutation.UnlockedStories(); ok {
		_spec.SetField(usercharacterconfig.FieldUnlockedStories, field.TypeJSON, value)
		_node.UnlockedStories = value
	}
	if value, ok := _c.mutation.UnlockedExpressions(); ok {
		_spec.SetField(usercharacterconfig.FieldUnlockedExpressions, field.TypeJSON, value)
		_node.UnlockedExpressions = value
	}
	if value, ok := _c.mutation.UnlockedDeepNightMode(); ok {
		_spec.SetField(usercharacterconfig.FieldUnlockedDeepNightMode, field.TypeBool, value)
		_node.UnlockedDeepNightMode = value
	}
	if value, ok := _c.mutation.TotalMessages(); ok {
		_spec.SetField(usercharacterconfig.FieldTotalMessages, field.TypeInt, value)
		_node.TotalMessages = value
	}
	if value, ok := _c.mutation.TotalGoalsCompleted(); ok {
		_spec.SetField(usercharacterconfig.FieldTotalGoalsCompleted, field.TypeInt, value)
		_node.TotalGoalsCompleted = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(usercharacterconfig.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.IsFavorite(); ok {
		_spec.SetField(usercharacterconfig.FieldIsFavorite, field.TypeBool, value)
		_node.IsFavorite = value
	}
	if value, ok := _c.mutation.SwitchCountThisMonth(); ok {
		_spec.SetField(usercharacterconfig.FieldSwitchCountThisMonth, field.TypeInt, value)
		_node.SwitchCountThisMonth = value
	}
	if value, ok := _c.mutation.LastSwitchDate(); ok {
		_spec.SetField(usercharacterconfig.FieldLastSwitchDate, field.TypeTime, value)
		_node.LastSwitchDate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usercharacterconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usercharacterconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserCharacterConfigCreateBulk is the builder for creating many UserCharacterConfig entities in bulk.
type UserCharacterConfigCreateBulk struct {
	config
	err      error
	builders []*UserCharacterConfigCreate
}

// Save creates the UserCharacterConfig entities in the database.
func (_c *UserCharacterConfigCreateBulk) Save(ctx context.Context) ([]*UserCharacterConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserCharacterConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserCharacterConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCharacterConfigCreateBulk) SaveX(ctx context.Context) []*UserCharacterConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCharacterConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCharacterConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
