// Code generated by ent, DO NOT EDIT.

package usercharacterconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the usercharacterconfig type in the database.
	Label = "user_character_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCharacterID holds the string denoting the character_id field in the database.
	FieldCharacterID = "character_id"
	// FieldCustomName holds the string denoting the custom_name field in the database.
	FieldCustomName = "custom_name"
	// FieldCustomAvatarURL holds the string denoting the custom_avatar_url field in the database.
	FieldCustomAvatarURL = "custom_avatar_url"
	// FieldIntimacyLevel holds the string denoting the intimacy_level field in the database.
	FieldIntimacyLevel = "intimacy_level"
	// FieldIntimacyScore holds the string denoting the intimacy_score field in the database.
	FieldIntimacyScore = "intimacy_score"
	// FieldUnlockedStories holds the string denoting the unlocked_stories field in the database.
	FieldUnlockedStories = "unlocked_stories"
	// FieldUnlockedExpressions holds the string denoting the unlocked_expressions field in the database.
	FieldUnlockedExpressions = "unlocked_expressions"
	// FieldUnlockedDeepNightMode holds the string denoting the unlocked_deep_night_mode field in the database.
	FieldUnlockedDeepNightMode = "unlocked_deep_night_mode"
	// FieldTotalMessages holds the string denoting the total_messages field in the database.
	FieldTotalMessages = "total_messages"
	// FieldTotalGoalsCompleted holds the string denoting the total_goals_completed field in the database.
	FieldTotalGoalsCompleted = "total_goals_completed"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldIsFavorite holds the string denoting the is_favorite field in the database.
	FieldIsFavorite = "is_favorite"
	// FieldSwitchCountThisMonth holds the string denoting the switch_count_this_month field in the database.
	FieldSwitchCountThisMonth = "switch_count_this_month"
	// FieldLastSwitchDate holds the string denoting the last_switch_date field in the database.
	FieldLastSwitchDate = "last_switch_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usercharacterconfig in the database.
	Table = "user_character_configs"
)

// Columns holds all SQL columns for usercharacterconfig fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCharacterID,
	FieldCustomName,
	FieldCustomAvatarURL,
	FieldIntimacyLevel,
	FieldIntimacyScore,
	FieldUnlockedStories,
	FieldUnlockedExpressions,
	FieldUnlockedDeepNightMode,
	FieldTotalMessages,
	FieldTotalGoalsCompleted,
	FieldIsActive,
	FieldIsFavorite,
	FieldSwitchCountThisMonth,
	FieldLastSwitchDate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CharacterIDValidator is a validator for the "character_id" field. It is called by the builders before save.
	CharacterIDValidator func(string) error
	// DefaultIntimacyLevel holds the default value on creation for the "intimacy_level" field.
	DefaultIntimacyLevel int
	// DefaultIntimacyScore holds the default value on creation for the "intimacy_score" field.
	DefaultIntimacyScore int
	// DefaultUnlockedStories holds the default value on creation for the "unlocked_stories" field.
	DefaultUnlockedStories []string
	// DefaultUnlockedExpressions holds the default value on creation for the "unlocked_expressions" field.
	DefaultUnlockedExpressions []string
	// DefaultUnlockedDeepNightMode holds the default value on creation for the "unlocked_deep_night_mode" field.
	DefaultUnlockedDeepNightMode bool
	// DefaultTotalMessages holds the default value on creation for the "total_messages" field.
	DefaultTotalMessages int
	// DefaultTotalGoalsCompleted holds the default value on creation for the "total_goals_completed" field.
	DefaultTotalGoalsCompleted int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultIsFavorite holds the default value on creation for the "is_favorite" field.
	DefaultIsFavorite bool
	// DefaultSwitchCountThisMonth holds the default value on creation for the "switch_count_this_month" field.
	DefaultSwitchCountThisMonth int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UserCharacterConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCharacterID orders the results by the character_id field.
func ByCharacterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCharacterID, opts...).ToFunc()
}

// ByCustomName orders the results by the custom_name field.
func ByCustomName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomName, opts...).ToFunc()
}

// ByCustomAvatarURL orders the results by the custom_avatar_url field.
func ByCustomAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomAvatarURL, opts...).ToFunc()
}

// ByIntimacyLevel orders the results by the intimacy_level field.
func ByIntimacyLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntimacyLevel, opts...).ToFunc()
}

// ByIntimacyScore orders the results by the intimacy_score field.
func ByIntimacyScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntimacyScore, opts...).ToFunc()
}

// ByUnlockedDeepNightMode orders the results by the unlocked_deep_night_mode field.
func ByUnlockedDeepNightMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlockedDeepNightMode, opts...).ToFunc()
}

// ByTotalMessages orders the results by the total_messages field.
func ByTotalMessages(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalMessages, opts...).ToFunc()
}

// ByTotalGoalsCompleted orders the results by the total_goals_completed field.
func ByTotalGoalsCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalGoalsCompleted, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByIsFavorite orders the results by the is_favorite field.
func ByIsFavorite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFavorite, opts...).ToFunc()
}

// BySwitchCountThisMonth orders the results by the switch_count_this_month field.
func BySwitchCountThisMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSwitchCountThisMonth, opts...).ToFunc()
}

// ByLastSwitchDate orders the results by the last_switch_date field.
func ByLastSwitchDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSwitchDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
