// Code generated by ent, DO NOT EDIT.

package celebritycharacter

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the celebritycharacter type in the database.
	Label = "celebrity_character"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameEn holds the string denoting the name_en field in the database.
	FieldNameEn = "name_en"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldEra holds the string denoting the era field in the database.
	FieldEra = "era"
	// FieldNationality holds the string denoting the nationality field in the database.
	FieldNationality = "nationality"
	// FieldFamousFor holds the string denoting the famous_for field in the database.
	FieldFamousFor = "famous_for"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldAvatarLottieURL holds the string denoting the avatar_lottie_url field in the database.
	FieldAvatarLottieURL = "avatar_lottie_url"
	// FieldStyleTags holds the string denoting the style_tags field in the database.
	FieldStyleTags = "style_tags"
	// FieldDistillate holds the string denoting the distillate field in the database.
	FieldDistillate = "distillate"
	// FieldQualityScore holds the string denoting the quality_score field in the database.
	FieldQualityScore = "quality_score"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsPremium holds the string denoting the is_premium field in the database.
	FieldIsPremium = "is_premium"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the celebritycharacter in the database.
	Table = "celebrity_characters"
)

// Columns holds all SQL columns for celebritycharacter fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldNameEn,
	FieldCategory,
	FieldEra,
	FieldNationality,
	FieldFamousFor,
	FieldAvatarURL,
	FieldAvatarLottieURL,
	FieldStyleTags,
	FieldDistillate,
	FieldQualityScore,
	FieldStatus,
	FieldIsPremium,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultFamousFor holds the default value on creation for the "famous_for" field.
	DefaultFamousFor []string
	// DefaultStyleTags holds the default value on creation for the "style_tags" field.
	DefaultStyleTags []string
	// DefaultDistillate holds the default value on creation for the "distillate" field.
	DefaultDistillate map[string]interface{}
	// DefaultQualityScore holds the default value on creation for the "quality_score" field.
	DefaultQualityScore float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultIsPremium holds the default value on creation for the "is_premium" field.
	DefaultIsPremium bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CelebrityCharacter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameEn orders the results by the name_en field.
func ByNameEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameEn, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByEra orders the results by the era field.
func ByEra(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEra, opts...).ToFunc()
}

// ByNationality orders the results by the nationality field.
func ByNationality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNationality, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByAvatarLottieURL orders the results by the avatar_lottie_url field.
func ByAvatarLottieURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarLottieURL, opts...).ToFunc()
}

// ByQualityScore orders the results by the quality_score field.
func ByQualityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityScore, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsPremium orders the results by the is_premium field.
func ByIsPremium(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPremium, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
