// Code generated by ent, DO NOT EDIT.

package celebritycharacter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lagom/lagom-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldName, v))
}

// NameEn applies equality check predicate on the "name_en" field. It's identical to NameEnEQ.
func NameEn(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldNameEn, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldCategory, v))
}

// Era applies equality check predicate on the "era" field. It's identical to EraEQ.
func Era(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldEra, v))
}

// Nationality applies equality check predicate on the "nationality" field. It's identical to NationalityEQ.
func Nationality(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldNationality, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarLottieURL applies equality check predicate on the "avatar_lottie_url" field. It's identical to AvatarLottieURLEQ.
func AvatarLottieURL(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldAvatarLottieURL, v))
}

// QualityScore applies equality check predicate on the "quality_score" field. It's identical to QualityScoreEQ.
func QualityScore(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldQualityScore, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldStatus, v))
}

// IsPremium applies equality check predicate on the "is_premium" field. It's identical to IsPremiumEQ.
func IsPremium(v bool) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldIsPremium, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldName, v))
}

// NameEnEQ applies the EQ predicate on the "name_en" field.
func NameEnEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldNameEn, v))
}

// NameEnNEQ applies the NEQ predicate on the "name_en" field.
func NameEnNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldNameEn, v))
}

// NameEnIn applies the In predicate on the "name_en" field.
func NameEnIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldNameEn, vs...))
}

// NameEnNotIn applies the NotIn predicate on the "name_en" field.
func NameEnNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldNameEn, vs...))
}

// NameEnGT applies the GT predicate on the "name_en" field.
func NameEnGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldNameEn, v))
}

// NameEnGTE applies the GTE predicate on the "name_en" field.
func NameEnGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldNameEn, v))
}

// NameEnLT applies the LT predicate on the "name_en" field.
func NameEnLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldNameEn, v))
}

// NameEnLTE applies the LTE predicate on the "name_en" field.
func NameEnLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldNameEn, v))
}

// NameEnContains applies the Contains predicate on the "name_en" field.
func NameEnContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldNameEn, v))
}

// NameEnHasPrefix applies the HasPrefix predicate on the "name_en" field.
func NameEnHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldNameEn, v))
}

// NameEnHasSuffix applies the HasSuffix predicate on the "name_en" field.
func NameEnHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldNameEn, v))
}

// NameEnIsNil applies the IsNil predicate on the "name_en" field.
func NameEnIsNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIsNull(FieldNameEn))
}

// NameEnNotNil applies the NotNil predicate on the "name_en" field.
func NameEnNotNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotNull(FieldNameEn))
}

// NameEnEqualFold applies the EqualFold predicate on the "name_en" field.
func NameEnEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldNameEn, v))
}

// NameEnContainsFold applies the ContainsFold predicate on the "name_en" field.
func NameEnContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldNameEn, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldCategory, v))
}

// EraEQ applies the EQ predicate on the "era" field.
func EraEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldEra, v))
}

// EraNEQ applies the NEQ predicate on the "era" field.
func EraNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldEra, v))
}

// EraIn applies the In predicate on the "era" field.
func EraIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldEra, vs...))
}

// EraNotIn applies the NotIn predicate on the "era" field.
func EraNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldEra, vs...))
}

// EraGT applies the GT predicate on the "era" field.
func EraGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldEra, v))
}

// EraGTE applies the GTE predicate on the "era" field.
func EraGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldEra, v))
}

// EraLT applies the LT predicate on the "era" field.
func EraLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldEra, v))
}

// EraLTE applies the LTE predicate on the "era" field.
func EraLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldEra, v))
}

// EraContains applies the Contains predicate on the "era" field.
func EraContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldEra, v))
}

// EraHasPrefix applies the HasPrefix predicate on the "era" field.
func EraHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldEra, v))
}

// EraHasSuffix applies the HasSuffix predicate on the "era" field.
func EraHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldEra, v))
}

// EraIsNil applies the IsNil predicate on the "era" field.
func EraIsNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIsNull(FieldEra))
}

// EraNotNil applies the NotNil predicate on the "era" field.
func EraNotNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotNull(FieldEra))
}

// EraEqualFold applies the EqualFold predicate on the "era" field.
func EraEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldEra, v))
}

// EraContainsFold applies the ContainsFold predicate on the "era" field.
func EraContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldEra, v))
}

// NationalityEQ applies the EQ predicate on the "nationality" field.
func NationalityEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldNationality, v))
}

// NationalityNEQ applies the NEQ predicate on the "nationality" field.
func NationalityNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldNationality, v))
}

// NationalityIn applies the In predicate on the "nationality" field.
func NationalityIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldNationality, vs...))
}

// NationalityNotIn applies the NotIn predicate on the "nationality" field.
func NationalityNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldNationality, vs...))
}

// NationalityGT applies the GT predicate on the "nationality" field.
func NationalityGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldNationality, v))
}

// NationalityGTE applies the GTE predicate on the "nationality" field.
func NationalityGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldNationality, v))
}

// NationalityLT applies the LT predicate on the "nationality" field.
func NationalityLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldNationality, v))
}

// NationalityLTE applies the LTE predicate on the "nationality" field.
func NationalityLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldNationality, v))
}

// NationalityContains applies the Contains predicate on the "nationality" field.
func NationalityContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldNationality, v))
}

// NationalityHasPrefix applies the HasPrefix predicate on the "nationality" field.
func NationalityHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldNationality, v))
}

// NationalityHasSuffix applies the HasSuffix predicate on the "nationality" field.
func NationalityHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldNationality, v))
}

// NationalityIsNil applies the IsNil predicate on the "nationality" field.
func NationalityIsNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIsNull(FieldNationality))
}

// NationalityNotNil applies the NotNil predicate on the "nationality" field.
func NationalityNotNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotNull(FieldNationality))
}

// NationalityEqualFold applies the EqualFold predicate on the "nationality" field.
func NationalityEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldNationality, v))
}

// NationalityContainsFold applies the ContainsFold predicate on the "nationality" field.
func NationalityContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldNationality, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldAvatarURL, v))
}

// AvatarLottieURLEQ applies the EQ predicate on the "avatar_lottie_url" field.
func AvatarLottieURLEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldAvatarLottieURL, v))
}

// AvatarLottieURLNEQ applies the NEQ predicate on the "avatar_lottie_url" field.
func AvatarLottieURLNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldAvatarLottieURL, v))
}

// AvatarLottieURLIn applies the In predicate on the "avatar_lottie_url" field.
func AvatarLottieURLIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldAvatarLottieURL, vs...))
}

// AvatarLottieURLNotIn applies the NotIn predicate on the "avatar_lottie_url" field.
func AvatarLottieURLNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldAvatarLottieURL, vs...))
}

// AvatarLottieURLGT applies the GT predicate on the "avatar_lottie_url" field.
func AvatarLottieURLGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldAvatarLottieURL, v))
}

// AvatarLottieURLGTE applies the GTE predicate on the "avatar_lottie_url" field.
func AvatarLottieURLGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldAvatarLottieURL, v))
}

// AvatarLottieURLLT applies the LT predicate on the "avatar_lottie_url" field.
func AvatarLottieURLLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldAvatarLottieURL, v))
}

// AvatarLottieURLLTE applies the LTE predicate on the "avatar_lottie_url" field.
func AvatarLottieURLLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldAvatarLottieURL, v))
}

// AvatarLottieURLContains applies the Contains predicate on the "avatar_lottie_url" field.
func AvatarLottieURLContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldAvatarLottieURL, v))
}

// AvatarLottieURLHasPrefix applies the HasPrefix predicate on the "avatar_lottie_url" field.
func AvatarLottieURLHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldAvatarLottieURL, v))
}

// AvatarLottieURLHasSuffix applies the HasSuffix predicate on the "avatar_lottie_url" field.
func AvatarLottieURLHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldAvatarLottieURL, v))
}

// AvatarLottieURLIsNil applies the IsNil predicate on the "avatar_lottie_url" field.
func AvatarLottieURLIsNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIsNull(FieldAvatarLottieURL))
}

// AvatarLottieURLNotNil applies the NotNil predicate on the "avatar_lottie_url" field.
func AvatarLottieURLNotNil() predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotNull(FieldAvatarLottieURL))
}

// AvatarLottieURLEqualFold applies the EqualFold predicate on the "avatar_lottie_url" field.
func AvatarLottieURLEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldAvatarLottieURL, v))
}

// AvatarLottieURLContainsFold applies the ContainsFold predicate on the "avatar_lottie_url" field.
func AvatarLottieURLContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldAvatarLottieURL, v))
}

// QualityScoreEQ applies the EQ predicate on the "quality_score" field.
func QualityScoreEQ(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldQualityScore, v))
}

// QualityScoreNEQ applies the NEQ predicate on the "quality_score" field.
func QualityScoreNEQ(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldQualityScore, v))
}

// QualityScoreIn applies the In predicate on the "quality_score" field.
func QualityScoreIn(vs ...float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldQualityScore, vs...))
}

// QualityScoreNotIn applies the NotIn predicate on the "quality_score" field.
func QualityScoreNotIn(vs ...float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldQualityScore, vs...))
}

// QualityScoreGT applies the GT predicate on the "quality_score" field.
func QualityScoreGT(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldQualityScore, v))
}

// QualityScoreGTE applies the GTE predicate on the "quality_score" field.
func QualityScoreGTE(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldQualityScore, v))
}

// QualityScoreLT applies the LT predicate on the "quality_score" field.
func QualityScoreLT(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldQualityScore, v))
}

// QualityScoreLTE applies the LTE predicate on the "quality_score" field.
func QualityScoreLTE(v float64) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldQualityScore, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldContainsFold(FieldStatus, v))
}

// IsPremiumEQ applies the EQ predicate on the "is_premium" field.
func IsPremiumEQ(v bool) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldIsPremium, v))
}

// IsPremiumNEQ applies the NEQ predicate on the "is_premium" field.
func IsPremiumNEQ(v bool) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldIsPremium, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CelebrityCharacter) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CelebrityCharacter) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CelebrityCharacter) predicate.CelebrityCharacter {
	return predicate.CelebrityCharacter(sql.NotPredicates(p))
}
