// Code generated by ent, DO NOT EDIT.

package dailycompletion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldUserID, v))
}

// HabitID applies equality check predicate on the "habit_id" field. It's identical to HabitIDEQ.
func HabitID(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldHabitID, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldDate, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldCompletedAt, v))
}

// QualityScore applies equality check predicate on the "quality_score" field. It's identical to QualityScoreEQ.
func QualityScore(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldQualityScore, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldNote, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldUserID, v))
}

// HabitIDEQ applies the EQ predicate on the "habit_id" field.
func HabitIDEQ(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldHabitID, v))
}

// HabitIDNEQ applies the NEQ predicate on the "habit_id" field.
func HabitIDNEQ(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldHabitID, v))
}

// HabitIDIn applies the In predicate on the "habit_id" field.
func HabitIDIn(vs ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldHabitID, vs...))
}

// HabitIDNotIn applies the NotIn predicate on the "habit_id" field.
func HabitIDNotIn(vs ...uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldHabitID, vs...))
}

// HabitIDGT applies the GT predicate on the "habit_id" field.
func HabitIDGT(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldHabitID, v))
}

// HabitIDGTE applies the GTE predicate on the "habit_id" field.
func HabitIDGTE(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldHabitID, v))
}

// HabitIDLT applies the LT predicate on the "habit_id" field.
func HabitIDLT(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldHabitID, v))
}

// HabitIDLTE applies the LTE predicate on the "habit_id" field.
func HabitIDLTE(v uuid.UUID) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldHabitID, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldDate, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldCompletedAt, v))
}

// QualityScoreEQ applies the EQ predicate on the "quality_score" field.
func QualityScoreEQ(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldQualityScore, v))
}

// QualityScoreNEQ applies the NEQ predicate on the "quality_score" field.
func QualityScoreNEQ(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldQualityScore, v))
}

// QualityScoreIn applies the In predicate on the "quality_score" field.
func QualityScoreIn(vs ...int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldQualityScore, vs...))
}

// QualityScoreNotIn applies the NotIn predicate on the "quality_score" field.
func QualityScoreNotIn(vs ...int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldQualityScore, vs...))
}

// QualityScoreGT applies the GT predicate on the "quality_score" field.
func QualityScoreGT(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldQualityScore, v))
}

// QualityScoreGTE applies the GTE predicate on the "quality_score" field.
func QualityScoreGTE(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldQualityScore, v))
}

// QualityScoreLT applies the LT predicate on the "quality_score" field.
func QualityScoreLT(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldQualityScore, v))
}

// QualityScoreLTE applies the LTE predicate on the "quality_score" field.
func QualityScoreLTE(v int) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldQualityScore, v))
}

// QualityScoreIsNil applies the IsNil predicate on the "quality_score" field.
func QualityScoreIsNil() predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIsNull(FieldQualityScore))
}

// QualityScoreNotNil applies the NotNil predicate on the "quality_score" field.
func QualityScoreNotNil() predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotNull(FieldQualityScore))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.FieldContainsFold(FieldNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyCompletion) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyCompletion) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyCompletion) predicate.DailyCompletion {
	return predicate.DailyCompletion(sql.NotPredicates(p))
}
