// Code generated by ent, DO NOT EDIT.

package microaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the microaction type in the database.
	Label = "micro_action"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHabitID holds the string denoting the habit_id field in the database.
	FieldHabitID = "habit_id"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldDayInPhase holds the string denoting the day_in_phase field in the database.
	FieldDayInPhase = "day_in_phase"
	// FieldActionText holds the string denoting the action_text field in the database.
	FieldActionText = "action_text"
	// FieldEstimatedDuration holds the string denoting the estimated_duration field in the database.
	FieldEstimatedDuration = "estimated_duration"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the microaction in the database.
	Table = "micro_actions"
)

// Columns holds all SQL columns for microaction fields.
var Columns = []string{
	FieldID,
	FieldHabitID,
	FieldPhase,
	FieldDayInPhase,
	FieldActionText,
	FieldEstimatedDuration,
	FieldIsDefault,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PhaseValidator is a validator for the "phase" field. It is called by the builders before save.
	PhaseValidator func(int) error
	// DayInPhaseValidator is a validator for the "day_in_phase" field. It is called by the builders before save.
	DayInPhaseValidator func(int) error
	// ActionTextValidator is a validator for the "action_text" field. It is called by the builders before save.
	ActionTextValidator func(string) error
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MicroAction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHabitID orders the results by the habit_id field.
func ByHabitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHabitID, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByDayInPhase orders the results by the day_in_phase field.
func ByDayInPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayInPhase, opts...).ToFunc()
}

// ByActionText orders the results by the action_text field.
func ByActionText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionText, opts...).ToFunc()
}

// ByEstimatedDuration orders the results by the estimated_duration field.
func ByEstimatedDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedDuration, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
