// Code generated by ent, DO NOT EDIT.

package microaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldID, id))
}

// HabitID applies equality check predicate on the "habit_id" field. It's identical to HabitIDEQ.
func HabitID(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldHabitID, v))
}

// Phase applies equality check predicate on the "phase" field. It's identical to PhaseEQ.
func Phase(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldPhase, v))
}

// DayInPhase applies equality check predicate on the "day_in_phase" field. It's identical to DayInPhaseEQ.
func DayInPhase(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldDayInPhase, v))
}

// ActionText applies equality check predicate on the "action_text" field. It's identical to ActionTextEQ.
func ActionText(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldActionText, v))
}

// EstimatedDuration applies equality check predicate on the "estimated_duration" field. It's identical to EstimatedDurationEQ.
func EstimatedDuration(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldEstimatedDuration, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldIsDefault, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldCreatedAt, v))
}

// HabitIDEQ applies the EQ predicate on the "habit_id" field.
func HabitIDEQ(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldHabitID, v))
}

// HabitIDNEQ applies the NEQ predicate on the "habit_id" field.
func HabitIDNEQ(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldHabitID, v))
}

// HabitIDIn applies the In predicate on the "habit_id" field.
func HabitIDIn(vs ...uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldHabitID, vs...))
}

// HabitIDNotIn applies the NotIn predicate on the "habit_id" field.
func HabitIDNotIn(vs ...uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldHabitID, vs...))
}

// HabitIDGT applies the GT predicate on the "habit_id" field.
func HabitIDGT(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldHabitID, v))
}

// HabitIDGTE applies the GTE predicate on the "habit_id" field.
func HabitIDGTE(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldHabitID, v))
}

// HabitIDLT applies the LT predicate on the "habit_id" field.
func HabitIDLT(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldHabitID, v))
}

// HabitIDLTE applies the LTE predicate on the "habit_id" field.
func HabitIDLTE(v uuid.UUID) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldHabitID, v))
}

// PhaseEQ applies the EQ predicate on the "phase" field.
func PhaseEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldPhase, v))
}

// PhaseNEQ applies the NEQ predicate on the "phase" field.
func PhaseNEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldPhase, v))
}

// PhaseIn applies the In predicate on the "phase" field.
func PhaseIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldPhase, vs...))
}

// PhaseNotIn applies the NotIn predicate on the "phase" field.
func PhaseNotIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldPhase, vs...))
}

// PhaseGT applies the GT predicate on the "phase" field.
func PhaseGT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldPhase, v))
}

// PhaseGTE applies the GTE predicate on the "phase" field.
func PhaseGTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldPhase, v))
}

// PhaseLT applies the LT predicate on the "phase" field.
func PhaseLT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldPhase, v))
}

// PhaseLTE applies the LTE predicate on the "phase" field.
func PhaseLTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldPhase, v))
}

// DayInPhaseEQ applies the EQ predicate on the "day_in_phase" field.
func DayInPhaseEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldDayInPhase, v))
}

// DayInPhaseNEQ applies the NEQ predicate on the "day_in_phase" field.
func DayInPhaseNEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldDayInPhase, v))
}

// DayInPhaseIn applies the In predicate on the "day_in_phase" field.
func DayInPhaseIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldDayInPhase, vs...))
}

// DayInPhaseNotIn applies the NotIn predicate on the "day_in_phase" field.
func DayInPhaseNotIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldDayInPhase, vs...))
}

// DayInPhaseGT applies the GT predicate on the "day_in_phase" field.
func DayInPhaseGT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldDayInPhase, v))
}

// DayInPhaseGTE applies the GTE predicate on the "day_in_phase" field.
func DayInPhaseGTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldDayInPhase, v))
}

// DayInPhaseLT applies the LT predicate on the "day_in_phase" field.
func DayInPhaseLT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldDayInPhase, v))
}

// DayInPhaseLTE applies the LTE predicate on the "day_in_phase" field.
func DayInPhaseLTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldDayInPhase, v))
}

// ActionTextEQ applies the EQ predicate on the "action_text" field.
func ActionTextEQ(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldActionText, v))
}

// ActionTextNEQ applies the NEQ predicate on the "action_text" field.
func ActionTextNEQ(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldActionText, v))
}

// ActionTextIn applies the In predicate on the "action_text" field.
func ActionTextIn(vs ...string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldActionText, vs...))
}

// ActionTextNotIn applies the NotIn predicate on the "action_text" field.
func ActionTextNotIn(vs ...string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldActionText, vs...))
}

// ActionTextGT applies the GT predicate on the "action_text" field.
func ActionTextGT(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldActionText, v))
}

// ActionTextGTE applies the GTE predicate on the "action_text" field.
func ActionTextGTE(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldActionText, v))
}

// ActionTextLT applies the LT predicate on the "action_text" field.
func ActionTextLT(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldActionText, v))
}

// ActionTextLTE applies the LTE predicate on the "action_text" field.
func ActionTextLTE(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldActionText, v))
}

// ActionTextContains applies the Contains predicate on the "action_text" field.
func ActionTextContains(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldContains(FieldActionText, v))
}

// ActionTextHasPrefix applies the HasPrefix predicate on the "action_text" field.
func ActionTextHasPrefix(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldHasPrefix(FieldActionText, v))
}

// ActionTextHasSuffix applies the HasSuffix predicate on the "action_text" field.
func ActionTextHasSuffix(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldHasSuffix(FieldActionText, v))
}

// ActionTextEqualFold applies the EqualFold predicate on the "action_text" field.
func ActionTextEqualFold(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEqualFold(FieldActionText, v))
}

// ActionTextContainsFold applies the ContainsFold predicate on the "action_text" field.
func ActionTextContainsFold(v string) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldContainsFold(FieldActionText, v))
}

// EstimatedDurationEQ applies the EQ predicate on the "estimated_duration" field.
func EstimatedDurationEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldEstimatedDuration, v))
}

// EstimatedDurationNEQ applies the NEQ predicate on the "estimated_duration" field.
func EstimatedDurationNEQ(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldEstimatedDuration, v))
}

// EstimatedDurationIn applies the In predicate on the "estimated_duration" field.
func EstimatedDurationIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldEstimatedDuration, vs...))
}

// EstimatedDurationNotIn applies the NotIn predicate on the "estimated_duration" field.
func EstimatedDurationNotIn(vs ...int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldEstimatedDuration, vs...))
}

// EstimatedDurationGT applies the GT predicate on the "estimated_duration" field.
func EstimatedDurationGT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldEstimatedDuration, v))
}

// EstimatedDurationGTE applies the GTE predicate on the "estimated_duration" field.
func EstimatedDurationGTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldEstimatedDuration, v))
}

// EstimatedDurationLT applies the LT predicate on the "estimated_duration" field.
func EstimatedDurationLT(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldEstimatedDuration, v))
}

// EstimatedDurationLTE applies the LTE predicate on the "estimated_duration" field.
func EstimatedDurationLTE(v int) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldEstimatedDuration, v))
}

// EstimatedDurationIsNil applies the IsNil predicate on the "estimated_duration" field.
func EstimatedDurationIsNil() predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIsNull(FieldEstimatedDuration))
}

// EstimatedDurationNotNil applies the NotNil predicate on the "estimated_duration" field.
func EstimatedDurationNotNil() predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotNull(FieldEstimatedDuration))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldIsDefault, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MicroAction {
	return predicate.MicroAction(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MicroAction) predicate.MicroAction {
	return predicate.MicroAction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MicroAction) predicate.MicroAction {
	return predicate.MicroAction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MicroAction) predicate.MicroAction {
	return predicate.MicroAction(sql.NotPredicates(p))
}
