// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"entgo.io/ent/dialect"
	"github.com/google/wire"
	"github.com/lagom/lagom-server/config"
	"github.com/lagom/lagom-server/ent"
	"github.com/lagom/lagom-server/internal/handler"
	"github.com/lagom/lagom-server/internal/pkg/ai"
	"github.com/lagom/lagom-server/internal/pkg/jwt"
	"github.com/lagom/lagom-server/internal/pkg/redis"
	"github.com/lagom/lagom-server/internal/service"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp 初始化应用（由 Wire 生成）
func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	client, err := ProvideEntClient(configConfig)
	if err != nil {
		return nil, err
	}
	redisConfig := ProvideRedisConfig(configConfig)
	redisClient, err := redis.New(redisConfig)
	if err != nil {
		return nil, err
	}
	manager := ProvideJWTManager(configConfig)
	authService := service.NewAuthService(configConfig, client, manager, redisClient)
	authHandler := handler.NewAuthHandler(authService)
	deepSeekClient := ProvideDeepSeekClient(configConfig)
	aiService := service.NewAIService(configConfig, client, deepSeekClient)
	chatHandler := handler.NewChatHandler(aiService)
	habitService := service.NewHabitService(configConfig, client)
	habitHandler := handler.NewHabitHandler(habitService)
	characterService := service.NewCharacterService(configConfig, client)
	characterHandler := handler.NewCharacterHandler(characterService)
	app := New(configConfig, client, redisClient, manager, authHandler, chatHandler, habitHandler, characterHandler)
	return app, nil
}

// wire.go:

// ProvideEntClient 提供 ent 数据库客户端
func ProvideEntClient(cfg *config.Config) (*ent.Client, error) {
	return ent.Open(dialect.Postgres, cfg.Database.DSN)
}

// ProvideJWTManager 提供 JWT 管理器
func ProvideJWTManager(cfg *config.Config) *jwt.Manager {
	return jwt.NewManager(cfg.JWT.Secret)
}

// ProvideDeepSeekClient 提供 DeepSeek AI 客户端
func ProvideDeepSeekClient(cfg *config.Config) *ai.DeepSeekClient {
	return ai.NewDeepSeekClient(cfg.AI.DeepSeekKey)
}

// ProvideRedisConfig 提取 Redis 配置
func ProvideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

// AppSet 是完整的应用依赖集合
var AppSet = wire.NewSet(config.Load, ProvideEntClient,

	ProvideJWTManager,
	ProvideDeepSeekClient,
	ProvideRedisConfig, redis.New, service.NewAuthService, service.NewAIService, service.NewHabitService, service.NewCharacterService, handler.NewAuthHandler, handler.NewChatHandler, handler.NewHabitHandler, handler.NewCharacterHandler, New,
)
