// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lagom/lagom-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// AppleID applies equality check predicate on the "apple_id" field. It's identical to AppleIDEQ.
func AppleID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAppleID, v))
}

// GoogleID applies equality check predicate on the "google_id" field. It's identical to GoogleIDEQ.
func GoogleID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGoogleID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// SubscriptionTier applies equality check predicate on the "subscription_tier" field. It's identical to SubscriptionTierEQ.
func SubscriptionTier(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSubscriptionTier, v))
}

// SubscriptionUntil applies equality check predicate on the "subscription_until" field. It's identical to SubscriptionUntilEQ.
func SubscriptionUntil(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSubscriptionUntil, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// AppleIDEQ applies the EQ predicate on the "apple_id" field.
func AppleIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAppleID, v))
}

// AppleIDNEQ applies the NEQ predicate on the "apple_id" field.
func AppleIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAppleID, v))
}

// AppleIDIn applies the In predicate on the "apple_id" field.
func AppleIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAppleID, vs...))
}

// AppleIDNotIn applies the NotIn predicate on the "apple_id" field.
func AppleIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAppleID, vs...))
}

// AppleIDGT applies the GT predicate on the "apple_id" field.
func AppleIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAppleID, v))
}

// AppleIDGTE applies the GTE predicate on the "apple_id" field.
func AppleIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAppleID, v))
}

// AppleIDLT applies the LT predicate on the "apple_id" field.
func AppleIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAppleID, v))
}

// AppleIDLTE applies the LTE predicate on the "apple_id" field.
func AppleIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAppleID, v))
}

// AppleIDContains applies the Contains predicate on the "apple_id" field.
func AppleIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAppleID, v))
}

// AppleIDHasPrefix applies the HasPrefix predicate on the "apple_id" field.
func AppleIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAppleID, v))
}

// AppleIDHasSuffix applies the HasSuffix predicate on the "apple_id" field.
func AppleIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAppleID, v))
}

// AppleIDIsNil applies the IsNil predicate on the "apple_id" field.
func AppleIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAppleID))
}

// AppleIDNotNil applies the NotNil predicate on the "apple_id" field.
func AppleIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAppleID))
}

// AppleIDEqualFold applies the EqualFold predicate on the "apple_id" field.
func AppleIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAppleID, v))
}

// AppleIDContainsFold applies the ContainsFold predicate on the "apple_id" field.
func AppleIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAppleID, v))
}

// GoogleIDEQ applies the EQ predicate on the "google_id" field.
func GoogleIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGoogleID, v))
}

// GoogleIDNEQ applies the NEQ predicate on the "google_id" field.
func GoogleIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGoogleID, v))
}

// GoogleIDIn applies the In predicate on the "google_id" field.
func GoogleIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldGoogleID, vs...))
}

// GoogleIDNotIn applies the NotIn predicate on the "google_id" field.
func GoogleIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGoogleID, vs...))
}

// GoogleIDGT applies the GT predicate on the "google_id" field.
func GoogleIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldGoogleID, v))
}

// GoogleIDGTE applies the GTE predicate on the "google_id" field.
func GoogleIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGoogleID, v))
}

// GoogleIDLT applies the LT predicate on the "google_id" field.
func GoogleIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldGoogleID, v))
}

// GoogleIDLTE applies the LTE predicate on the "google_id" field.
func GoogleIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGoogleID, v))
}

// GoogleIDContains applies the Contains predicate on the "google_id" field.
func GoogleIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldGoogleID, v))
}

// GoogleIDHasPrefix applies the HasPrefix predicate on the "google_id" field.
func GoogleIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldGoogleID, v))
}

// GoogleIDHasSuffix applies the HasSuffix predicate on the "google_id" field.
func GoogleIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldGoogleID, v))
}

// GoogleIDIsNil applies the IsNil predicate on the "google_id" field.
func GoogleIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldGoogleID))
}

// GoogleIDNotNil applies the NotNil predicate on the "google_id" field.
func GoogleIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldGoogleID))
}

// GoogleIDEqualFold applies the EqualFold predicate on the "google_id" field.
func GoogleIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldGoogleID, v))
}

// GoogleIDContainsFold applies the ContainsFold predicate on the "google_id" field.
func GoogleIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldGoogleID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPasswordHash, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// SubscriptionTierEQ applies the EQ predicate on the "subscription_tier" field.
func SubscriptionTierEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierNEQ applies the NEQ predicate on the "subscription_tier" field.
func SubscriptionTierNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierIn applies the In predicate on the "subscription_tier" field.
func SubscriptionTierIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierNotIn applies the NotIn predicate on the "subscription_tier" field.
func SubscriptionTierNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierGT applies the GT predicate on the "subscription_tier" field.
func SubscriptionTierGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSubscriptionTier, v))
}

// SubscriptionTierGTE applies the GTE predicate on the "subscription_tier" field.
func SubscriptionTierGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSubscriptionTier, v))
}

// SubscriptionTierLT applies the LT predicate on the "subscription_tier" field.
func SubscriptionTierLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSubscriptionTier, v))
}

// SubscriptionTierLTE applies the LTE predicate on the "subscription_tier" field.
func SubscriptionTierLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSubscriptionTier, v))
}

// SubscriptionTierContains applies the Contains predicate on the "subscription_tier" field.
func SubscriptionTierContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSubscriptionTier, v))
}

// SubscriptionTierHasPrefix applies the HasPrefix predicate on the "subscription_tier" field.
func SubscriptionTierHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSubscriptionTier, v))
}

// SubscriptionTierHasSuffix applies the HasSuffix predicate on the "subscription_tier" field.
func SubscriptionTierHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSubscriptionTier, v))
}

// SubscriptionTierEqualFold applies the EqualFold predicate on the "subscription_tier" field.
func SubscriptionTierEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSubscriptionTier, v))
}

// SubscriptionTierContainsFold applies the ContainsFold predicate on the "subscription_tier" field.
func SubscriptionTierContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSubscriptionTier, v))
}

// SubscriptionUntilEQ applies the EQ predicate on the "subscription_until" field.
func SubscriptionUntilEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSubscriptionUntil, v))
}

// SubscriptionUntilNEQ applies the NEQ predicate on the "subscription_until" field.
func SubscriptionUntilNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSubscriptionUntil, v))
}

// SubscriptionUntilIn applies the In predicate on the "subscription_until" field.
func SubscriptionUntilIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldSubscriptionUntil, vs...))
}

// SubscriptionUntilNotIn applies the NotIn predicate on the "subscription_until" field.
func SubscriptionUntilNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSubscriptionUntil, vs...))
}

// SubscriptionUntilGT applies the GT predicate on the "subscription_until" field.
func SubscriptionUntilGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldSubscriptionUntil, v))
}

// SubscriptionUntilGTE applies the GTE predicate on the "subscription_until" field.
func SubscriptionUntilGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSubscriptionUntil, v))
}

// SubscriptionUntilLT applies the LT predicate on the "subscription_until" field.
func SubscriptionUntilLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldSubscriptionUntil, v))
}

// SubscriptionUntilLTE applies the LTE predicate on the "subscription_until" field.
func SubscriptionUntilLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSubscriptionUntil, v))
}

// SubscriptionUntilIsNil applies the IsNil predicate on the "subscription_until" field.
func SubscriptionUntilIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSubscriptionUntil))
}

// SubscriptionUntilNotNil applies the NotNil predicate on the "subscription_until" field.
func SubscriptionUntilNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSubscriptionUntil))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
